MODULE OUTPUT_ANALS
!*************************************************
! OUTPUT THE ANALYSIS RESULT
! HISTORY: SEPTEMBER 2007, CODED by WEI LI.
!          FEBRUARY 2008,  ZHONGJIE HE.
!*************************************************

  USE PRMTRS_STMAS
  USE GENERALTOOLS
  
  USE READ_BACKGRD   , ONLY : ORI_LON, ORI_LAT, END_LON, END_LAT,BK0
  USE DRAWCOUNTOUR   , ONLY : DRCONTOUR, DRCONTOUR_2D
  USE READOBSERVES   , ONLY : X_RADAR, Y_RADAR

  PUBLIC    OUTPTLAPS, OUTPUTANA, TMPOUTPUT
  PRIVATE   BKGMEMRLS, DRCONTOUR_0, RADIALWND
!***************************************************
!!COMMENT:
!   THIS MODULE IS USED BY THE MAIN PROGRAM, TO OUTPUT THE ANALIZED FIELDS.
!   SUBROUTINES:
!      OUTPTLAPS : OUTPUT THE ANALIZED FIELDS TO LAPS.
!      OUTPUTANA : OUTPUT THE ANALIZED FILEDS TO SOME FILES AND DRAW SOME PICTURES TO CHECK.
!      TMPOUTPUT : OUTPUT THE ANALIZED FILEDS TO SOME FILES AND DRAW SOME PICTURES TO CHECK.
!      BKGMEMRLS : RELEASE THE MEMORYS.
!      DRCONTOUR_0: WRITE SOME FIELDS INTO THE FILES WITH THE FORMAT OF SURFER( A SOFTWARE TO DRAW PICTURES).
!      RADIALWND : TRANSLATE THE U, V FIELDS TO RADIAL WIND FIELD, USED TO DRAW PICTURE.

CONTAINS

SUBROUTINE OUTPTLAPS
!*************************************************
! GET BACKGROUND FOR ANALYSIS
! HISTORY: SEPTEMBER 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER  :: I,J,K,T,S,LN
  CHARACTER(LEN=200) :: DR
  REAL     :: XB(MAXGRID(1)),YB(MAXGRID(2)),ZB(MAXGRID(3)),TB(MAXGRID(4))
  REAL     :: XF(FCSTGRD(1)),YF(FCSTGRD(2)),ZF(FCSTGRD(3)),TF(FCSTGRD(4))
  REAL     :: ANA(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),FCSTGRD(4),NUMSTAT)
  INTEGER  :: FG(MAXDIMS),MG(MAXDIMS)
  REAL     :: Z1(1),T1(1),Z2(1),T2(1),DX,DY

  ! PARAMETERS FOR CONVERTING Q, P AND T TO RH (COPIED FROM lib/degrib/rrpr.F90:
  real, parameter :: svp1=611.2
  real, parameter :: svp2=17.67
  real, parameter :: svp3=29.65
  real, parameter :: svpt0=273.15
  real, parameter :: eps = 0.622
  real            :: tmp,sph

  ! VARIABLES NEEDED FOR LAPS: YUANFU
  CHARACTER*9   :: A9
  CHARACTER*3   :: WN(3)=(/'U3','V3','OM'/)	! WIND NAMES
  CHARACTER*3   :: SN(2)=(/'SU','SV'/)		! WIND NAMES
  CHARACTER*4   :: WU(3)=(/'M/S ','M/S ','PA/S'/) ! WIND UNITS
  CHARACTER*125 :: WC(3)=(/'3DWIND','3DWIND','3DWIND'/) ! WIND COMMENTS
  CHARACTER*125 :: SC(2)=(/'SFCWIND','SFCWIND'/) ! SFC WIND COMMENTS
  INTEGER       :: I4,ST,IFRAME
  ! REAL          :: LA(FCSTGRD(1),FCSTGRD(2)),LO(FCSTGRD(1),FCSTGRD(2))
  ! REAL          :: TP(FCSTGRD(1),FCSTGRD(2)),DS,LV(FCSTGRD(3))
  REAL          :: DS,LV(FCSTGRD(3))

  REAL          :: HT(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))
  REAL          :: RH(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))		! RELATIVE HUMIDITY
  REAL          :: T3(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))
  REAL          :: W3(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),2)	! 3D WIND: UV
  REAL          :: SF(FCSTGRD(1),FCSTGRD(2),2)	! SURFACE WIND: UV
  REAL          :: SP(FCSTGRD(1),FCSTGRD(2))	! SURFACE PRESSURE
  REAL          :: HEIGHT_TO_ZCOORD3,RM,A,DLNP
! --------------------
  DO I=1,FCSTGRD(1)
    XF(I)=(I-1)*1.0D0
  ENDDO
  DO J=1,FCSTGRD(2)
    YF(J)=(J-1)*1.0D0
  ENDDO
  DX=((FCSTGRD(1)-1)*1.0D0)/((MAXGRID(1)-1)*1.0D0)
  DO I=1,MAXGRID(1)
    XB(I)=XF(1)+(I-1)*DX
  ENDDO
  DY=((FCSTGRD(2)-1)*1.0D0)/((MAXGRID(2)-1)*1.0D0)
  DO J=1,MAXGRID(2)
    YB(J)=YF(1)+(J-1)*DY
  ENDDO
  
!===========
  DO K=1,FCSTGRD(3)
    ZF(K)=Z_FCSTGD(K)
  ENDDO
  DO K=1,MAXGRID(3)
    ZB(K)=Z_MAXGID(K)
  ENDDO
!=================
!  OPEN(2,FILE=DR(1:LN)//'P_LEVEL.DAT',STATUS='OLD',ACTION='READ')
!  DO K=1,MAXGRID(3)
!    READ(2,*)ZB(K)
!  ENDDO
!  CLOSE(2)
!==================
  DO T=1,FCSTGRD(4)
    TF(T)=(ITIME2(2)-ITIME2(1))*(T-1)/(FCSTGRD(4)-1)
  ENDDO
  DO T=1,MAXGRID(4)
    TB(T)=(ITIME2(2)-ITIME2(1))*(T-1)/(MAXGRID(4)-1)
  ENDDO

  ! HEIGHT FROM HYDROSTATIC:
  ! WRITE(15,*) MAXGRID,GRDBKGD0(1:MAXGRID(1),1:MAXGRID(2),1:MAXGRID(3),2,3)
  ! DO K=2,MAXGRID(3)
  !   DO J=1,MAXGRID(2)
   !    DO I=1,MAXGRID(1)
   !      GRDBKGD0(I,J,K,1:MAXGRID(4),3) = GRDBKGD0(I,J,K-1,1:MAXGRID(4),3)-287.0/9.8*0.5* &
! 	  (GRDBKGD0(I,J,K,1:MAXGRID(4),4)+GRDBKGD0(I,J,K-1,1:MAXGRID(4),4))* &
   !        (LOG(PPM(K))-LOG(PPM(K-1)))
   !    ENDDO
   !  ENDDO
  ! ENDDO
  ! WRITE(15,*) MAXGRID,GRDBKGD0(1:MAXGRID(1),1:MAXGRID(2),1:MAXGRID(3),2,3)
  print*,'Increment: ',maxval(ABS(grdbkgd0(1:maxgrid(1),1:maxgrid(2),maxgrid(3),1:3,1)))
  print*,'Increment: ',maxval(ABS(grdbkgd0(1:maxgrid(1),1:maxgrid(2),maxgrid(3),1:3,2)))
  print*,'Increment: ',maxval(ABS(grdbkgd0(1:maxgrid(1),1:maxgrid(2),maxgrid(3),1:3,3)))
  print*,'Increment: ',maxval(ABS(grdbkgd0(1:maxgrid(1),1:maxgrid(2),maxgrid(3),1:3,4)))
  CALL BKGTOFINE(NUMSTAT,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,GRDBKGD0,ANA)

  ! ADD INCREMENT TO BK0:
  DO S=1,NUMSTAT
    DO T=1,FCSTGRD(4)
    DO K=1,FCSTGRD(3)
    DO J=1,FCSTGRD(2)
    DO I=1,FCSTGRD(1)
      BK0(I,J,K,T,S) = BK0(I,J,K,T,S)+ANA(I,J,K,T,S)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
print*,'Specific humidity low bound: ',minval(BK0(1:fcstgrd(1),1:fcstgrd(2),1:fcstgrd(3),2,5))

  CALL GET_GRID_SPACING_ACTUAL(LATITUDE((FCSTGRD(1)-1)/2+1,(FCSTGRD(2)-1)/2+1), &
                                LONGITUD((FCSTGRD(1)-1)/2+1,(FCSTGRD(2)-1)/2+1),DS,ST)
  ! PRESSURE LEVELS:
  CALL GET_PRES_1D(LAPSI4T,FCSTGRD(3),LV,ST)
  CALL GET_R_MISSING_DATA(RM,ST)

  ! OUTPUT: WIND BY YUANFU --

  ! INTERPOLATE SURFACE WIND:
  ! HT = BK0(:,:,:,1,3)
  ! W3 = BK0(:,:,:,1,1:2)
  ! DO J=1,FCSTGRD(2)
  ! DO I=1,FCSTGRD(1)
  !   SP(I,J) = HEIGHT_TO_ZCOORD3(TP(I,J),HT,LV,FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),I,J,ST)
  !   K = INT(SP(I,J))
  !   A = SP(I,J)-K
  !   SF(I,J,1:2) = (1.0-A)*W3(I,J,K,1:2)+A*W3(I,J,K+1,1:2)
  ! ENDDO
  ! ENDDO

  ! WRITE SURFACE WIND (THIS IS ALSO REQIRED TO PLOT 3D WIND ON-THE-FLY):
  ! CALL PUT_LAPS_MULTI_2D(I4,'lwm',SN,WU,SC,SF,FCSTGRD(1),FCSTGRD(2),2,ST)
  ! CALL WIND_POST_PROCESS(I4,'lw3',WN,WU,WC,W3(1,1,1,1),W3(1,1,1,2), &
  !                        FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),3,SF(1,1,1),SF(1,1,2),TP, &
  !                        LA,LO,DS,SP,RM,.TRUE.,ST)

  ! WRITE TEMPERATURE: W3 ARRAY SERVES AS WORKING ARRAY:
  ! T3(:,:,:) = BK0(:,:,:,1,4)
  ! CALL WRITE_TEMP_ANAL(I4,FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),T3,HT,W3,A9,ST)

  ! OUTPUT TIME FRAME:
  IFRAME = 2	! TEMPORARY TESTING BY YUANFU XIE

  ! USE LAPS WRITE BALANCED FIELD:
  ! VERTICAL VELOCITY:
  T3 = 0.0 ! ALSO TEST FOR X Y BOUNDARIES: EXTRAPOLATE LATER YUANFU
  ! CENTER FINITE DIFFERNCE REQUIRE 2*DELTA X (or Y):
  DS = 2.0*DS
  DO K=2,FCSTGRD(3)
    DO J=2,FCSTGRD(2)-1
      DO I=2,FCSTGRD(1)-1
        ! V3(K)=V3(K-1)-DZ*(UX+VY):
        T3(I,J,K) = T3(I,J,K-1) - 0.5* &
          (LV(K)-LV(K-1))*( &
          ! (BK0(I,J,K,FCSTGRD(4),3)-BK0(I,J,K-1,FCSTGRD(4),3))*( &
          (BK0(I+1,J,K,IFRAME,1)-BK0(I-1,J,K,IFRAME,1))/DS+ &
          (BK0(I,J+1,K,IFRAME,2)-BK0(I,J-1,K,IFRAME,2))/DS )
        ! BK0(I,J,K,FCSTGRD(4),2) =  1.0e5*(BK0(I+1,J,K,FCSTGRD(4),3)-BK0(I-1,J,K,FCSTGRD(4),3))/DS
        ! BK0(I,J,K,FCSTGRD(4),1) = -1.0e5*(BK0(I,J+1,K,FCSTGRD(4),3)-BK0(I,J-1,K,FCSTGRD(4),3))/DS

	! Test vorticity:
	! T3(I,J,K) = (BK0(I+1,J,K,FCSTGRD(4),2)-BK0(I-1,J,K,FCSTGRD(4),2))/DS- &
        !             (BK0(I,J+1,K,FCSTGRD(4),1)-BK0(I,J-1,K,FCSTGRD(4),1))/DS
        ! T3(I,J,K) = T3(I,J,K)*1.0e4
      ENDDO
    ENDDO
  ENDDO

  ! CONVERTED FROM P, Q T:
  DO K=1,FCSTGRD(3)
    DO J=1,FCSTGRD(2)
      DO I=1,FCSTGRD(1)
        sph = BK0(I,J,K,IFRAME,5)*0.001
        tmp = BK0(I,J,K,IFRAME,4)
        RH(I,J,K) = 1.E2 * (LV(k)*sph/(sph*(1.-eps) + eps))/(svp1*exp(svp2*(tmp-svpt0)/(tmp-svp3)))
      ENDDO
    ENDDO
  ENDDO

  ! HEIGHT FROM HYDROSTATIC:
  ! BK0(1:FCSTGRD(1),1:FCSTGRD(2),1,IFRAME,3) = 0.0
  goto 1
  DO K=4,FCSTGRD(3)
    DO J=1,FCSTGRD(2)
      DO I=1,FCSTGRD(1)
        BK0(I,J,K,IFRAME,3) = BK0(I,J,K-1,IFRAME,3)-287.0/9.8*0.5* &
	  (BK0(I,J,K,IFRAME,4)+BK0(I,J,K-1,IFRAME,4))* &
          (LOG(LV(K))-LOG(LV(K-1)))
      ENDDO
    ENDDO
  ENDDO
1 continue

  ! KG/KG FOR BALANCE NETCDF:
  BK0(1:FCSTGRD(1),1:FCSTGRD(2),1:FCSTGRD(3),IFRAME,5) = 0.001* &
    BK0(1:FCSTGRD(1),1:FCSTGRD(2),1:FCSTGRD(3),IFRAME,5)
  CALL WRITE_BAL_LAPS(LAPSI4T,BK0(1,1,1,IFRAME,3),BK0(1,1,1,IFRAME,1), &
                          BK0(1,1,1,IFRAME,2),BK0(1,1,1,IFRAME,4), &
                          T3,RH,BK0(1,1,1,IFRAME,5),FCSTGRD(1),FCSTGRD(2), &
                          FCSTGRD(3),LV,ST)

  ! WRITE TEMPERATURE AND WIND INTO LAPSPRD:
  CALL WRITE_TEMP_ANAL(LAPSI4T,FCSTGRD(1),FCSTGRD(2),FCSTGRD(3), &
       BK0(1,1,1,IFRAME,4),BK0(1,1,1,IFRAME,3),DR,ST)

  ! WRITE WIND BY COMPONENTS:
  CALL PUT_LAPS_MULTI_3D_JACKET(LAPSI4T,'lw3',WN,WU,WC, &
                     BK0(1,1,1,IFRAME,1),BK0(1,1,1,IFRAME,2),T3, &
                     FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),3,ST)

  ! END OF OUTPUT TO LAPS BY YUANFU
  CALL BKGMEMRLS
  DEALLOCATE(Z_FCSTGD)
  ! FINALLY RELEASE THE BACKGROUND ARRAYS: BY YUANFU
  DEALLOCATE(BK0)
  ! FINALLY RELEASE MEMORY FOR LAT/LON/TOPO:
  DEALLOCATE(LATITUDE, LONGITUD, TOPOGRPH)
  RETURN
END SUBROUTINE OUTPTLAPS

SUBROUTINE OUTPUTANA
!*************************************************
! GET BACKGROUND FOR ANALYSIS
! HISTORY: SEPTEMBER 2007, CODED by WEI LI.
!          FEBRUARY 2008, BY ZHONGJIE HE
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER  :: I,J,K,L,T,S,LN
  CHARACTER(LEN=200) :: DR
  REAL     :: XB(MAXGRID(1)),YB(MAXGRID(2)),ZB(MAXGRID(3)),TB(MAXGRID(4))
  REAL     :: XF(FCSTGRD(1)),YF(FCSTGRD(2)),ZF(FCSTGRD(3)),TF(FCSTGRD(4))
  REAL     :: BK1(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),FCSTGRD(4),NUMSTAT)
  INTEGER  :: FG(MAXDIMS),MG(MAXDIMS)
  REAL     :: Z1(1),T1(1),Z2(1),T2(1),DX,DY,DT

! ADDED BY ZHONGJIE HE==========
  REAL  :: UU(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))
  REAL  :: VV(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))
  REAL  :: WW(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))
  REAL  :: UV(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3))
  REAL  :: W0(FCSTGRD(1),FCSTGRD(2),FCSTGRD(3),FCSTGRD(4))

  REAL  :: D1,D2,DD
!===============================

! --------------------
  DO I=1,FCSTGRD(1)
    XF(I)=(I-1)*1.0D0
  ENDDO
  DO J=1,FCSTGRD(2)
    YF(J)=(J-1)*1.0D0
  ENDDO
  DX=((FCSTGRD(1)-1)*1.0D0)/((MAXGRID(1)-1)*1.0D0)
  DO I=1,MAXGRID(1)
    XB(I)=XF(1)+(I-1)*DX
  ENDDO
  DY=((FCSTGRD(2)-1)*1.0D0)/((MAXGRID(2)-1)*1.0D0)
  DO J=1,MAXGRID(2)
    YB(J)=YF(1)+(J-1)*DY
  ENDDO
  CALL GET_DIRECTORY('static',DR,LN)
!================
  DO K=1,FCSTGRD(3)
    ZF(K)=Z_FCSTGD(K)
  ENDDO
  DO K=1,MAXGRID(3)
    ZB(K)=Z_MAXGID(K)
  ENDDO
!=============== JUST FOR TEST DATA 
!  OPEN(2,FILE=DR(1:LN)//'P_LEVEL.DAT',STATUS='OLD',ACTION='READ')
!  DO K=1,MAXGRID(3)
!    READ(2,*)ZB(K)
!  ENDDO
!  CLOSE(2)
  
!  DO K=1,MAXGRID(3)
!    ZB(K)=ZF(1)+(K-1)*(ZF(FCSTGRD(3))-ZF(1))/(MAXGRID(3)-1.0)
!  ENDDO
! ===============

  DO T=1,FCSTGRD(4)
    TF(T)=(T-1)*1.0
  ENDDO
  IF(MAXGRID(4).GE.2) DT=((FCSTGRD(4)-1)*1.0)/(MAXGRID(4)-1.0)
  DO T=1,MAXGRID(4)
    TB(T)=TF(1)+(T-1)*DT
  ENDDO

! ADDED BY ZHONGJIE HE==========

!  CALL FCST2BKGD(NUMDIMS,NGPTOBS,NUMSTAT,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,DIFFTOUT,BK1)
  CALL BKGTOFINE(NUMSTAT,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,GRDBKGD0,BK1)
!  CALL FCST2BKGD(NUMDIMS,NGPTOBS,1,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,WWWOUT,W0)
  CALL BKGTOFINE(1,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,WWWOUT,W0)

  DEALLOCATE(DIFFTOUT)
  DEALLOCATE(WWWOUT)

  DO K=1,FCSTGRD(3)
  DO J=1,FCSTGRD(2)
  DO I=1,FCSTGRD(1)
    UU(I,J,K)=BK1(I,J,K,1,U_CMPNNT)
    VV(I,J,K)=BK1(I,J,K,1,V_CMPNNT)
!    WW(I,J,K)=W0(I,J,K,1)
!    D1=ORI_LON+(END_LON-ORI_LON)/FLOAT(FCSTGRD(1)-1)*(I-1)
!    D1=D1-X_RADAR
!    D2=ORI_LAT+(END_LAT-ORI_LAT)/FLOAT(FCSTGRD(2)-1)*(J-1)
!    D2=D2-Y_RADAR
!    DD=SQRT(D1*D1+D2*D2)
!    UV(I,J,K)=UU(I,J,K)*D1/DD+VV(I,J,K)*D2/DD
  ENDDO
  ENDDO
  ENDDO

  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,UU,'UD.GRD')
  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,VV,'VD.GRD')
!  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,WW,'WD.GRD')
!  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,UV,'RD.GRD')

!===============================

!  CALL FCST2BKGD(NUMDIMS,NGPTOBS,NUMSTAT,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,GRDBKGD0,BK1)
  CALL BKGTOFINE(NUMSTAT,MAXGRID,XB,YB,ZB,TB,FCSTGRD,XF,YF,ZF,TF,GRDBKGD0,BK1)

! ADDED BY ZHONGJIE HE==========
  DO K=1,FCSTGRD(3)
  DO J=1,FCSTGRD(2)
  DO I=1,FCSTGRD(1)
    UU(I,J,K)=BK1(I,J,K,1,U_CMPNNT)
    VV(I,J,K)=BK1(I,J,K,1,V_CMPNNT)
    WW(I,J,K)=W0(I,J,K,1)
!    D1=ORI_LON+(END_LON-ORI_LON)/FLOAT(FCSTGRD(1)-1)*(I-1)
!    D1=D1-X_RADAR
!    D2=ORI_LAT+(END_LAT-ORI_LAT)/FLOAT(FCSTGRD(2)-1)*(J-1)
!    D2=D2-Y_RADAR
!    DD=SQRT(D1*D1+D2*D2)
!    UV(I,J,K)=UU(I,J,K)*D1/DD+VV(I,J,K)*D2/DD
  ENDDO
  ENDDO
  ENDDO

  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,UU,'UA.GRD')
  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,VV,'VA.GRD')
  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,WW,'WA.GRD')
!  CALL DRCONTOUR(ORI_LON,END_LON,ORI_LAT,END_LAT,NUMDIMS,FCSTGRD,UV,'RA.GRD')
!===============================

  CALL BKGMEMRLS
  DEALLOCATE(Z_FCSTGD)
  DEALLOCATE(Z_MAXGID)


!============= to check the analysis field======
  OPEN(1,FILE='STMAS_ANAL.DAT',ACTION='WRITE')
    WRITE(1,*) FCSTGRD(1:4)
    DO L=1,FCSTGRD(4)
    DO K=1,FCSTGRD(3)
    DO J=1,FCSTGRD(2)
    DO I=1,FCSTGRD(1)
      WRITE(1,*) BK1(I,J,K,L,U_CMPNNT),BK1(I,J,K,L,V_CMPNNT),BK1(I,J,K,L,TEMPRTUR),W0(I,J,K,L)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  CLOSE(1)
!===========================================


  RETURN
END SUBROUTINE OUTPUTANA

SUBROUTINE TMPOUTPUT
!*************************************************
! OUTPUT ANALYSIS
! HISTORY: SEPTEMBER 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER  :: I,J,K,T,S
  INTEGER  :: IC,JC
! --------------------
  OPEN(2,FILE='ANALYSIS.DAT')
  DO S=1,NUMSTAT
    DO T=1,1      ! NUMGRID(4)
    DO K=1,1      ! NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      WRITE(2,*) GRDBKGD0(I,J,K,T,S)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  CLOSE(2)
!  CALL DRCONTOUR_0(PRESSURE,'Z.GRD')
  CALL DRCONTOUR_0(U_CMPNNT,'U.GRD')
  CALL DRCONTOUR_0(V_CMPNNT,'V.GRD')
!  CALL DRCONTOUR_0(4,'T.GRD')
  IC=(NUMGRID(1)+1)/2
  JC=(NUMGRID(2)+1)/2
  CALL RADIALWND(IC,JC)
  CALL BKGMEMRLS
  RETURN
END SUBROUTINE TMPOUTPUT

SUBROUTINE BKGMEMRLS
!*************************************************
! RELEASE MEMORY FOR BACKGROUND ARRAY
! HISTORY: SEPTEMBER 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
  DEALLOCATE(GRDBKGD0)
  DEALLOCATE(XX0)
  DEALLOCATE(YY0)
  DEALLOCATE(CR0)
  DEALLOCATE(DG0)
  DEALLOCATE(DN0)
  IF(IFPCDNT.EQ.0 .OR. IFPCDNT.EQ.2)THEN
    DEALLOCATE(ZZ0)
    DEALLOCATE(ZZB)
  ELSEIF(IFPCDNT.EQ.1)THEN
    DEALLOCATE(PP0,PPM)
  ENDIF
  RETURN
END SUBROUTINE BKGMEMRLS

SUBROUTINE DRCONTOUR_0(S,FN)
!*************************************************
! DRAW THE ANALYSIS (AFFILIATE)
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER   :: I,J,K,T,S,IU
  REAL      :: MX,MN
  CHARACTER(LEN=5) :: FN
! --------------------
  K=2 !(NUMGRID(3)+1)/2 !NUMGRID(3)
  T=(NUMGRID(4)+1)/2 !NUMGRID(4) !1
  IU=2
  OPEN(IU,FILE=FN,STATUS='UNKNOWN')
  MX=-1000.0
  MN=1000.0
  DO I=1,NUMGRID(1)
  DO J=1,NUMGRID(2)
    IF(GRDBKGD0(I,J,K,T,S).LT.9000.0)THEN
      IF(GRDBKGD0(I,J,K,T,S).GT.MX)MX=GRDBKGD0(I,J,K,T,S)
      IF(GRDBKGD0(I,J,K,T,S).LT.MN)MN=GRDBKGD0(I,J,K,T,S)
    ENDIF
  ENDDO
  ENDDO
  WRITE(IU,'(A4)')'DSAA'
  WRITE(IU,'(2I4)')NUMGRID(1),NUMGRID(2)
  WRITE(IU,*)ORIPSTN(1),ORIPSTN(1)+(NUMGRID(1)-1)*GRDSPAC(1)
  WRITE(IU,*)ORIPSTN(2),ORIPSTN(2)+(NUMGRID(2)-1)*GRDSPAC(2)
  WRITE(IU,*)MN,MX
  DO I=1,NUMGRID(1)
  DO J=1,NUMGRID(2)
    IF(GRDBKGD0(I,J,K,T,S).GT.9000.0)GRDBKGD0(I,J,K,T,S)=2.E38
  ENDDO
  ENDDO
  DO J=1,NUMGRID(2)
    WRITE(IU,*)(GRDBKGD0(I,J,K,T,S),I=1,NUMGRID(1))
  ENDDO
  CLOSE(IU)
  RETURN
END SUBROUTINE DRCONTOUR_0

SUBROUTINE RADIALWND(IC,JC)
!*************************************************
! DRAW RADIAL WIND (AFFILIATE)
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER  :: IU,IC,JC,I,J,K,T
  REAL     :: DX,DY,DD,MN,MX
  REAL     :: UV(NUMGRID(1),NUMGRID(2),NUMGRID(3),NUMGRID(4))
! --------------------
  DO T=1,NUMGRID(4)
  DO K=1,NUMGRID(3)
  DO J=1,NUMGRID(2)
  DO I=1,NUMGRID(1)
    IF(I.EQ.IC.AND.J.EQ.JC)THEN
      UV(I,J,K,T)=2.E38
      CYCLE
    ENDIF
    DX=1.0D0*(I-IC)
    DY=1.0D0*(J-JC)
    DD=SQRT(DX*DX+DY*DY)
    UV(I,J,K,T)=GRDBKGD0(I,J,K,T,U_CMPNNT)*DX/DD+GRDBKGD0(I,J,K,T,V_CMPNNT)*DY/DD
  ENDDO
  ENDDO
  ENDDO
  ENDDO
  K=(NUMGRID(3)+1)/2 !NUMGRID(3)
  T=(NUMGRID(4)+1)/2 !NUMGRID(4) !1
  IU=2
  OPEN(IU,FILE='RADIAL.GRD',STATUS='UNKNOWN')
  MX=-1000.0
  MN=1000.0
  DO I=1,NUMGRID(1)
  DO J=1,NUMGRID(2)
    IF(UV(I,J,K,T).LT.9000.0)THEN
      IF(UV(I,J,K,T).GT.MX)MX=UV(I,J,K,T)
      IF(UV(I,J,K,T).LT.MN)MN=UV(I,J,K,T)
    ENDIF
  ENDDO
  ENDDO
  WRITE(IU,'(A4)')'DSAA'
  WRITE(IU,'(2I4)')NUMGRID(1),NUMGRID(2)
  WRITE(IU,*)ORIPSTN(1),ORIPSTN(1)+(NUMGRID(1)-1)*GRDSPAC(1)
  WRITE(IU,*)ORIPSTN(2),ORIPSTN(2)+(NUMGRID(2)-1)*GRDSPAC(2)
  WRITE(IU,*)MN,MX
  DO I=1,NUMGRID(1)
  DO J=1,NUMGRID(2)
    IF(UV(I,J,K,T).GT.9000.0)UV(I,J,K,T)=2.E38
  ENDDO
  ENDDO
  DO J=1,NUMGRID(2)
    WRITE(IU,*)(UV(I,J,K,T),I=1,NUMGRID(1))
  ENDDO
  CLOSE(IU)
  RETURN
END SUBROUTINE RADIALWND

END MODULE OUTPUT_ANALS
