MODULE PRMTRS_STMAS
  IMPLICIT NONE
  INTEGER(KIND=4),  PARAMETER :: MAXDIMS=4          ! NUMBER OF TOTAL DIMENSION
  INTEGER(KIND=4)             :: BGTHOBS            ! NOT USE BACKGROUND UNTIL NOBSGRID LESS THAN BGTHOBS
  INTEGER(KIND=4)             :: GRDLEVL            ! GRID LEVEL
  INTEGER(KIND=4)             :: NUMGRID(MAXDIMS)   ! NUMBER OF GRID FOR EVERY DIMENSION
  INTEGER(KIND=4)             :: MAXGRID(MAXDIMS)   ! MAX NUMBER OF GRID FOR EVERY DIMENSION
  INTEGER(KIND=4)             :: NTMPGRD(MAXDIMS)   ! NUMBER OF OLD GRID FOR EVERY DIMENSION
  INTEGER(KIND=4)             :: FCSTGRD(MAXDIMS)   ! NUMBER OF OLD GRID FOR EVERY DIMENSION
  INTEGER(KIND=4)             :: NUMDIMS            ! NUMBER OF DIMENSION VALID
  INTEGER(KIND=4)             :: NGPTOBS            ! NUMBER OF GRID POINT PER OBSERVATION
  INTEGER(KIND=4)             :: NUMSTAT            ! NUMBER OF STATE
  INTEGER(KIND=4)             :: NALLOBS            ! NUMBER OF TOTAL OBSERVATION VALID
  INTEGER(KIND=4),ALLOCATABLE :: NOBSTAT(:)         ! NUMBER OF VARIETY OF OBSERVATION VALID
  INTEGER(KIND=4)             :: NUMVARS            ! NUMBER OF TOTAL CONTROL VARIABLES VALID
  INTEGER(KIND=4)             :: IFBKGND            ! WHETHER USE BACKGROUND OR NOT, 1 IS YES, 0 IS NOT
  INTEGER(KIND=4)             :: IFBOUND            ! WHETHER USE BOUND OR NOT, 1 IS YES, 0 IS NOT
  INTEGER(KIND=4)             :: IFPCDNT            ! WHETHER USE PURE PRESSURE COORDINATE, 1 IS YES, 0 IS NOT
  INTEGER(KIND=4)             :: FNSTGRD            ! THE FINEST GRID LEVEL
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL0X(:)         ! INITIAL X DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL0Y(:)         ! INITIAL Y DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL0Z(:)         ! INITIAL Z DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL0T(:)         ! INITIAL T DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL_X(:)         ! X DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL_Y(:)         ! Y DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL_Z(:)         ! Z DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)   ,ALLOCATABLE :: PENAL_T(:)         ! T DIRECTION PENALTY COEFFICENT
  REAL(KIND=8)                :: PNLT0PU            ! INITIAL GEOSTROPHIC BALANCE PENALTY COEFFICENT, FOR P AND U
  REAL(KIND=8)                :: PNLT0PV            ! INITIAL GEOSTROPHIC BALANCE PENALTY COEFFICENT, FOR P AND V
  REAL(KIND=8)                :: PNLT_PU            ! GEOSTROPHIC BALANCE PENALTY COEFFICENT, FOR P AND U
  REAL(KIND=8)                :: PNLT_PV            ! GEOSTROPHIC BALANCE PENALTY COEFFICENT, FOR P AND V
  REAL(KIND=8)                :: GRDSPAC(MAXDIMS)   ! GRID SPACING
  REAL(KIND=8)                :: ORIPSTN(MAXDIMS)   ! ORIGINAL POSITION OF THE STUDY DOMAIN
  REAL(KIND=8)                :: COSTFUN            ! COST FUNCTION
  REAL(KIND=8)   ,ALLOCATABLE :: GRADINT(:,:,:,:,:) ! GRADIENT OF COST FUNCTION
  CHARACTER(LEN=100)          :: OBSFILE            ! OBSERVATION FILE NAME

  INTEGER(KIND=4)             :: U_CMPNNT           ! U COMPONENT
  INTEGER(KIND=4)             :: V_CMPNNT           ! V COMPONENT
  INTEGER(KIND=4)             :: W_CMPNNT           ! W COMPONENT
  INTEGER(KIND=4)             :: PRESSURE           ! PRESSURE
  INTEGER(KIND=4)             :: TEMPRTUR           ! TEMPERATURE

  REAL(KIND=8)   ,ALLOCATABLE :: WWW(:,:,:,:)       ! W COMPONENT
  REAL(KIND=8)   ,ALLOCATABLE :: XXX(:,:)           ! DISTANCE OF HORIZONTAL DIMENSION 1
  REAL(KIND=8)   ,ALLOCATABLE :: YYY(:,:)           ! DISTANCE OF HORIZONTAL DIMENSION 2
  REAL(KIND=8)   ,ALLOCATABLE :: ZZZ(:,:,:,:)       ! HEIGHT OF GENERAL VERTICAL COORDINATE
  REAL(KIND=8)   ,ALLOCATABLE :: PPP(:)             ! PRESSURE VERTICAL COORDINATE
  REAL(KIND=8)   ,ALLOCATABLE :: COR(:,:)           ! CORIOLIS FREQUENCY
  REAL(KIND=8)   ,ALLOCATABLE :: DEG(:,:)           ! DIRECTION ANGLE
  REAL(KIND=8)   ,ALLOCATABLE :: DEN(:,:,:,:)       ! DENSITY
  REAL(KIND=8)   ,ALLOCATABLE :: SCL(:)             ! SCALING THE PHYSICAL VARIABLE
  REAL(KIND=8)   ,ALLOCATABLE :: SL0(:)             ! DEFAULT SCALING THE PHYSICAL VARIABLE
  REAL(KIND=8)                :: SCP(5)             ! SCALING XXX,YYY,ZZZ OR PPP,COR,GRDBKGND
  REAL(KIND=8)                :: ORIVTCL
  REAL(KIND=8)   ,ALLOCATABLE :: XX0(:,:)           ! DISTANCE OF HORIZONTAL DIMENSION 1
  REAL(KIND=8)   ,ALLOCATABLE :: YY0(:,:)           ! DISTANCE OF HORIZONTAL DIMENSION 2
  REAL(KIND=8)   ,ALLOCATABLE :: ZZ0(:,:,:,:)       ! HEIGHT OF GENERAL VERTICAL COORDINATE
  REAL(KIND=8)   ,ALLOCATABLE :: PP0(:)             ! PRESSURE VERTICAL COORDINATE
  REAL(KIND=8)   ,ALLOCATABLE :: CR0(:,:)           ! CORIOLIS FREQUENCY
  REAL(KIND=8)   ,ALLOCATABLE :: DG0(:,:)           ! DIRECTION ANGLE
  REAL(KIND=8)   ,ALLOCATABLE :: DN0(:,:,:,:)       ! DENSITY
! FOR OBSERVATION
  REAL(KIND=8)                :: OBSRADAR           ! THE RATIO OF CONVENTION TO RADAR
  REAL(KIND=8)   ,ALLOCATABLE :: OBSPOSTN(:,:)      ! COORDINATE OF OBSERVATION POINT
  REAL(KIND=8)   ,ALLOCATABLE :: OBSCOEFF(:,:)      ! INTERPOLATION COEFFICENT
  INTEGER(KIND=4),ALLOCATABLE :: OBSIDXPC(:,:)      ! INDEX OF EVERY NODE PER CELL
  INTEGER(KIND=4),ALLOCATABLE :: OBSSTATE(:)        ! NUMBER OF OBSERVATION FOR EVERY STATE
  REAL(KIND=8)   ,ALLOCATABLE :: OBSVALUE(:)        ! OBSERVATION VALUE
  REAL(KIND=8)   ,ALLOCATABLE :: OBSERROR(:)        ! OBSERVATION ERROR
  REAL(KIND=8)   ,ALLOCATABLE :: OBSEINF1(:)        ! OBSERVATION EXTRA INFORMATION 1
  REAL(KIND=8)   ,ALLOCATABLE :: OBSEINF2(:)        ! OBSERVATION EXTRA INFORMATION 2
  REAL(KIND=8)   ,ALLOCATABLE :: OBSEINF3(:)        ! OBSERVATION EXTRA INFORMATION 3
! FOR GRID POINT VARIABLE
  REAL(KIND=8)   ,ALLOCATABLE :: GRDBKGD0(:,:,:,:,:)! GRID BACKGROUND VALUE
  REAL(KIND=8)   ,ALLOCATABLE :: GRDBKGND(:,:,:,:,:)! GRID BACKGROUND VALUE
  REAL(KIND=8)   ,ALLOCATABLE :: GRDANALS(:,:,:,:,:)! GRID ANALYSIS VALUE
  REAL(KIND=8)   ,ALLOCATABLE :: TMPANALS(:,:,:,:,:)! GRID ANALYSIS VALUE
END MODULE PRMTRS_STMAS
