MODULE POST_STMAS4D

  USE PRMTRS_STMAS

CONTAINS

SUBROUTINE PSTPROCSS
!*************************************************
! POST PROCESS
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
  CALL UNSCALING
  CALL RETRIEVAL
  CALL OBSMEMRLS
  CALL GRDMEMRLS
  RETURN
END SUBROUTINE PSTPROCSS

SUBROUTINE UNSCALING
!*************************************************
! UNSCALING EVERY ARRAY
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S,O,UU
! --------------------
  UU=U_CMPNNT
! UNSCALING XXX, YYY, ZZZ OR PPP, AND COR
  DO I=1,NUMGRID(1)
  DO J=1,NUMGRID(2)
    IF(PNLT0PU.GE.1.0E-10.OR.PNLT0PV.GE.1.0E-10)COR(I,J)=COR(I,J)*SCP(4)
    IF(NUMGRID(1).GE.2)XXX(I,J)=ORIPSTN(1)+XXX(I,J)*SCP(1)
    IF(NUMGRID(2).GE.2)YYY(I,J)=ORIPSTN(2)+YYY(I,J)*SCP(2)
  ENDDO
  ENDDO
  IF(IFPCDNT.EQ.0)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      ZZZ(I,J,K,T)=ORIVTCL+ZZZ(I,J,K,T)*SCP(3)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
    CLOSE(1)
  ELSEIF(IFPCDNT.EQ.1)THEN
    DO K=1,NUMGRID(3)
      PPP(K)=ORIVTCL+PPP(K)*SCP(3)
    ENDDO
  ENDIF
! UNSCALING THE OBSERVATIONS
  DO O=1,NALLOBS
    S=OBSSTATE(O)
    IF(S.LE.NUMSTAT)THEN
      OBSVALUE(O)=OBSVALUE(O)*SCL(S)
      OBSERROR(O)=OBSERROR(O)*SCL(S)
    ELSEIF(S.EQ.NUMSTAT+1)THEN  ! FOR RADAR
      OBSVALUE(O)=OBSVALUE(O)*SCL(UU)
      OBSERROR(O)=OBSERROR(O)*SCL(UU)
    ENDIF
  ENDDO
! UNSCALING GRID POINT VARIABLES
  DO S=1,NUMSTAT
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      GRDANALS(I,J,K,T,S)=GRDANALS(I,J,K,T,S)*SCL(S)
      GRDBKGND(I,J,K,T,S)=GRDBKGND(I,J,K,T,S)*SCL(S)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  RETURN
END SUBROUTINE UNSCALING

SUBROUTINE OBSMEMRLS
!*************************************************
! RELEASE OBSERVATIONS MEMORY
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
  IF(NALLOBS.GE.1)THEN
    DEALLOCATE(OBSPOSTN)
    DEALLOCATE(OBSCOEFF)
    DEALLOCATE(OBSIDXPC)
    DEALLOCATE(OBSVALUE)
    DEALLOCATE(OBSERROR)
    DEALLOCATE(OBSSTATE)
!    DEALLOCATE(OBSEINF1)
!    DEALLOCATE(OBSEINF2)
!    DEALLOCATE(OBSEINF3)
  ENDIF
  DEALLOCATE(PENAL_X)
  DEALLOCATE(PENAL_Y)
  DEALLOCATE(PENAL_Z)
  DEALLOCATE(PENAL_T)
  DEALLOCATE(PENAL0X)
  DEALLOCATE(PENAL0Y)
  DEALLOCATE(PENAL0Z)
  DEALLOCATE(PENAL0T)
  DEALLOCATE(SCL)
  DEALLOCATE(SL0)
  DEALLOCATE(NOBSTAT)
  RETURN
END SUBROUTINE OBSMEMRLS

SUBROUTINE GRDMEMRLS
!*************************************************
! MEMORY RELEASE FOR GRD ARRAY
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
  DEALLOCATE(WWW)
  DEALLOCATE(COR)
  DEALLOCATE(XXX)
  DEALLOCATE(YYY)
  DEALLOCATE(DEG)
  DEALLOCATE(DEN)
  IF(IFPCDNT.EQ.0)THEN
    DEALLOCATE(ZZZ)
  ELSEIF(IFPCDNT.EQ.1)THEN
    DEALLOCATE(PPP)
  ENDIF
  DEALLOCATE(GRDBKGND)
  DEALLOCATE(GRDANALS)
  DEALLOCATE(GRADINT)
  RETURN
END SUBROUTINE GRDMEMRLS

SUBROUTINE RETRIEVAL
!*************************************************
! RETRIEVAL THE ANALYSIS FIELD FOR OUTPUT
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S
! --------------------
  DO S=4,4
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      GRDBKGD0(I,J,K,T,S)=GRDBKGD0(I,J,K,T,S)-273.15D0
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  OPEN(2,FILE='DIFFERENCE.DAT')
  DO S=1,NUMSTAT
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      WRITE(2,*)GRDANALS(I,J,K,T,S)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  CLOSE(2)
  OPEN(2,FILE='BACKGROUND.DAT')
  DO S=1,NUMSTAT
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      WRITE(2,*)GRDBKGD0(I,J,K,T,S)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  CLOSE(2)
  DO S=1,NUMSTAT
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      GRDBKGD0(I,J,K,T,S)=GRDANALS(I,J,K,T,S)+GRDBKGD0(I,J,K,T,S)
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  RETURN
END SUBROUTINE RETRIEVAL

END MODULE POST_STMAS4D
