MODULE STMAS4D_CORE

  USE PRMTRS_STMAS
  USE GENERALTOOLS
  USE PREP_STMAS4D
  USE POST_STMAS4D

CONTAINS

SUBROUTINE MGANALYSS0
!*************************************************
! MULTI-GRID ANALYSIS
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: N
! --------------------
  PRINT*,'PREPROCSS'
  CALL PREPROCSS
  N=0
  GRDLEVL=0
  DO WHILE(.TRUE.)
    N=N+1
    GRDLEVL=GRDLEVL+1
    PRINT*,'NUMBER',GRDLEVL,'LEVEL GRID IS IN PROCESSING'
    CALL RDINITBGD
    PRINT*,'PHYSCPSTN'
    CALL PHYSCPSTN
    PRINT*,'GETCOEFFT'
    CALL GETCOEFFT
    IF(NUMVARS.EQ.0)EXIT
    PRINT*,'MINIMIZER'
    CALL MINIMIZER
    IF(GRDLEVL.EQ.FNSTGRD)EXIT
    IF(GRDLEVL.LE.4.OR.(N.GE.9.AND.GRDLEVL.GE.5))THEN
      PRINT*,'COAS2FINE'
      CALL COAS2FINE
    ELSE
      GRDLEVL=GRDLEVL-2
      PRINT*,'FINE2COAS'
      CALL FINE2COAS
    ENDIF
  ENDDO
  PRINT*,'PSTPROCSS'
  CALL PSTPROCSS
  RETURN
END SUBROUTINE MGANALYSS0

SUBROUTINE MGANALYSS
!*************************************************
! MULTI-GRID ANALYSIS
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
  PRINT*,'PREPROCSS'
  CALL PREPROCSS
  GRDLEVL=0
  DO WHILE(.TRUE.)
    GRDLEVL=GRDLEVL+1
    PRINT*,'NUMBER',GRDLEVL,'LEVEL GRID IS IN PROCESSING'
    CALL RDINITBGD
    PRINT*,'PHYSCPSTN'
    CALL PHYSCPSTN
    PRINT*,'GETCOEFFT'
    CALL GETCOEFFT
    IF(NUMVARS.EQ.0)EXIT
    PRINT*,'MINIMIZER'
    CALL MINIMIZER
    IF(GRDLEVL.EQ.FNSTGRD)EXIT
    PRINT*,'COAS2FINE'
    CALL COAS2FINE
  ENDDO
  PRINT*,'PSTPROCSS'
  CALL PSTPROCSS
  RETURN
END SUBROUTINE MGANALYSS

SUBROUTINE TMPMEMALC
!*************************************************
! MEMORY ALLOCATE FOR TMP ARRAY
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S,ER
! --------------------
  ALLOCATE(TMPANALS(NTMPGRD(1),NTMPGRD(2),NTMPGRD(3),NTMPGRD(4),NUMSTAT),STAT=ER)
  IF(ER.NE.0)STOP 'TMPANALS ALLOCATE WRONG'
  DO T=1,NTMPGRD(4)
  DO K=1,NTMPGRD(3)
  DO J=1,NTMPGRD(2)
  DO I=1,NTMPGRD(1)
    DO S=1,NUMSTAT
      TMPANALS(I,J,K,T,S)=GRDANALS(I,J,K,T,S)
    ENDDO
  ENDDO
  ENDDO
  ENDDO
  ENDDO
  RETURN
END SUBROUTINE TMPMEMALC

SUBROUTINE TMPMEMRLS
!*************************************************
! MEMORY RELEASE FOR TMP ARRAY
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
  DEALLOCATE(TMPANALS)
  RETURN
END SUBROUTINE TMPMEMRLS

SUBROUTINE GETCOEFFT
!*************************************************
! GET GRID POINT COEFFICENT FOR EVERY OBSERVATION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,O,M,N
  INTEGER(KIND=4) :: NP(MAXDIMS),NN(MAXDIMS)
  REAL(KIND=8)    :: AC(NUMDIMS,NGPTOBS),OC(NUMDIMS),CO(NGPTOBS)
! --------------------
! GET INTERPOLATION COEFFICENT
  DO O=1,NALLOBS
    DO N=1,MAXDIMS
      NP(N)=1
    ENDDO
    DO N=1,NUMDIMS
      NP(N)=IDINT((OBSPOSTN(N,O)-ORIPSTN(N))/GRDSPAC(N))+1
      IF(NP(N).EQ.NUMGRID(N).AND.NUMGRID(N).NE.1)NP(N)=NUMGRID(N)-1
    ENDDO
    DO N=1,MAXDIMS
      OBSIDXPC(N,O)=NP(N)
    ENDDO
    M=0
    DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
    DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
    DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
    DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
      NN(1)=I
      NN(2)=J
      NN(3)=K
      NN(4)=T
      M=M+1
      DO N=1,NUMDIMS
        AC(N,M)=NN(N)*1.0
      ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDDO
    DO N=1,NUMDIMS
      OC(N)=(OBSPOSTN(N,O)-ORIPSTN(N))/GRDSPAC(N)+1
    ENDDO
    CALL INTERPLTN(NUMDIMS,NGPTOBS,CO,AC,OC)
    DO M=1,NGPTOBS
      OBSCOEFF(M,O)=CO(M)
    ENDDO
  ENDDO
  RETURN
END SUBROUTINE GETCOEFFT

SUBROUTINE MINIMIZER
!*************************************************
! MINIMIZE THE COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4),PARAMETER :: MM=7,NNNN=499851
  CHARACTER(LEN=60) :: TA,CS
  LOGICAL           :: LS(4)
  INTEGER(KIND=4)   :: I0,IC,IP,IT,N,O,S,T,K,J,I
  INTEGER(KIND=4)   :: IS(44),NB(NUMVARS),IW(3*NUMVARS)
  INTEGER(KIND=4)   :: NN(MAXDIMS+1),NG(MAXDIMS+1),NC
  REAL(KIND=8)      :: FA,PG,MN(NUMSTAT),MX(NUMSTAT)
  REAL(KIND=8)      :: DS(29),LB(NUMVARS),UB(NUMVARS)
  REAL(KIND=8)      :: WA(2*MM*NUMVARS+4*NUMVARS+11*MM*MM+8*MM)
! --------------------
  IP=1
  FA=1.0d+2
  PG=1.0d-10
  DO N=1,NUMVARS
    NB(N)=0
    LB(N)=0.0
    UB(N)=0.0
  ENDDO
! BOUND
  IF(IFBOUND.EQ.1)THEN
    DO S=1,NUMSTAT
      MN(S)=1000.0
      MX(S)=-1000.0
    ENDDO
    DO N=1,MAXDIMS
      NG(N)=NUMGRID(N)
    ENDDO
    NG(MAXDIMS+1)=NUMSTAT
    DO O=1,NALLOBS
      S=OBSSTATE(O)
      IF(S.LE.NUMSTAT)THEN
        MN(S)=DMIN1(MN(S),OBSVALUE(O))
        MX(S)=DMAX1(MX(S),OBSVALUE(O))
      ELSEIF(S.EQ.NUMSTAT+1)THEN  ! FOR RADAR
        MN(S-NUMSTAT)=DMIN1(MN(S-NUMSTAT),OBSVALUE(O))
        MX(S-NUMSTAT)=DMAX1(MX(S-NUMSTAT),OBSVALUE(O))
        MN(S-NUMSTAT+1)=DMIN1(MN(S-NUMSTAT+1),OBSVALUE(O))
        MX(S-NUMSTAT+1)=DMAX1(MX(S-NUMSTAT+1),OBSVALUE(O))
      ENDIF
    ENDDO
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=1,NUMGRID(3)
      DO J=1,NUMGRID(2)
      DO I=1,NUMGRID(1)
        NN(1)=I
        NN(2)=J
        NN(3)=K
        NN(4)=T
        NN(MAXDIMS+1)=S
        CALL PSTN2NUMB(MAXDIMS+1,NN,NG,NC)
        IF(MN(S).LE.MX(S))THEN
          NB(NC)=2
          LB(NC)=MN(S)
          UB(NC)=MX(S)
        ELSE
          NB(NC)=0
          LB(NC)=0.0D0
          UB(NC)=0.0D0
        ENDIF
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
    IF(IFBKGND.EQ.1)THEN
      DO N=1,NUMVARS
        IF(NB(N).EQ.2)THEN
          LB(N)=DMIN1(LB(N),0.0D0)
          UB(N)=DMAX1(UB(N),0.0D0)
        ENDIF
      ENDDO
    ENDIF
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=1,NUMGRID(3)
      DO J=1,NUMGRID(2)
      DO I=1,NUMGRID(1)
        IF((NUMGRID(1).GT.1.AND.(I.EQ.1.OR.I.EQ.NUMGRID(1))).OR. &
           (NUMGRID(2).GT.1.AND.(J.EQ.1.OR.J.EQ.NUMGRID(2))).OR. &
           (NUMGRID(3).GT.1.AND.(K.EQ.1.OR.K.EQ.NUMGRID(3))).OR. &
           (NUMGRID(4).GT.1.AND.(T.EQ.1.OR.T.EQ.NUMGRID(4))))CYCLE
        NN(1)=I
        NN(2)=J
        NN(3)=K
        NN(4)=T
        NN(MAXDIMS+1)=S
        CALL PSTN2NUMB(MAXDIMS+1,NN,NG,NC)
        NB(NC)=0
        LB(NC)=0.0
        UB(NC)=0.0
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
! BOUND
  DO N=1,3*NUMVARS
    IW(N)=0
  ENDDO
  DO N=1,2*MM*NUMVARS+4*NUMVARS+11*MM*MM+8*MM
    WA(N)=0.0
  ENDDO
  TA='START'
  I0=0
  IC=0
  WRITE(*,9001)
  CALL COSTFUNCT
  CALL COSTGRADT
!  WRITE(8,*)'TOP FUNCTION =',COSTFUN
  ITERLOOP: DO WHILE (.TRUE.)
    CALL SETULB(NUMVARS,MM,GRDANALS,LB,UB,NB,COSTFUN,GRADINT,FA,PG,WA,IW, &
                TA,IP,CS,LS,IS,DS,IT)
    WRITE(100,*)GRDLEVL,IT
    IF(GRDLEVL.LE.6.AND.IT.GT.50)EXIT
    IF(GRDLEVL.GE.7.AND.IT.GT.5)EXIT
!    IF(GRDLEVL.EQ.1.AND.IT.EQ.1)CALL CHECK_F_G
    IF(TA(1:2).EQ.'FG')THEN
      CALL COSTFUNCT
      CALL COSTGRADT
      IC=IC+1
      CYCLE ITERLOOP
    ELSEIF(TA(1:5).EQ.'NEW_X')THEN
      IF(I0.EQ.0)THEN
        WRITE(*,1003)IS(30),IS(34),DS(13),COSTFUN
      ELSE
        WRITE(*,3001)IS(30),IS(34),DS(14),DS(13),COSTFUN
      ENDIF
      I0=I0+1
      CYCLE ITERLOOP
    ELSE
      IF(IP.LE.-1.AND.TA(1:4).NE.'STOP')WRITE(6,*)TA
      EXIT ITERLOOP
    ENDIF
  END DO ITERLOOP
  1003 FORMAT (2(1x,i4),5x,'-',3x,1p,2(1x,d10.3))
  9001 FORMAT (/,3x,'it',3x,'nf',2x,'stepl',5x,'projg',8x,'f')
  3001 FORMAT (2(1x,i4),1p,2x,d7.1,1p,2(1x,d10.3))
  CALL COSTFUNCT
  CALL COSTGRADT
  WRITE(8,*)'BOTTOM FUNCTION =',COSTFUN
  RETURN
END SUBROUTINE MINIMIZER

SUBROUTINE COSTFUNCT
!*************************************************
! CALCULATE COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S,O,M,N
  INTEGER(KIND=4) :: NP(MAXDIMS)
  REAL(KIND=8) :: HT,OI,HU,HV,DG
  REAL(KIND=8) :: CS(NUMSTAT),CM,CB
! --------------------
! INITIALIZATION
  COSTFUN=0.0
  DO S=1,NUMSTAT
    CS(S)=0.0
  ENDDO
  IF(NALLOBS.EQ.0)RETURN
  DO O=1,NALLOBS
    DO N=1,MAXDIMS
      NP(N)=OBSIDXPC(N,O)
    ENDDO
    S=OBSSTATE(O)
    OI=OBSERROR(O)**2
    OI=1.0/OI
    IF(S.LE.NUMSTAT)THEN
!   FOR CONVENTION OBSERVATION
      HT=0.0
      M=0
      DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
      DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
      DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
      DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
        M=M+1
        HT=HT+OBSCOEFF(M,O)*GRDANALS(I,J,K,T,S)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      COSTFUN=COSTFUN+(HT-OBSVALUE(O))*OI*(HT-OBSVALUE(O)) !/NOBSTAT(S)
      CS(S)=CS(S)+0.5*(HT-OBSVALUE(O))*OI*(HT-OBSVALUE(O)) !/NOBSTAT(S)
    ELSEIF(S.EQ.NUMSTAT+1)THEN
!   FOR RADAR OBSERVATION
      HU=0.0
      HV=0.0
      M=0
      DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
      DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
      DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
      DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
        M=M+1
        HU=HU+OBSCOEFF(M,O)*GRDANALS(I,J,K,T,S-NUMSTAT)
        HV=HV+OBSCOEFF(M,O)*GRDANALS(I,J,K,T,S-NUMSTAT+1)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      DG=OBSEINF1(O)
      HT=HU*DSIND(DG)+HV*DCOSD(DG)
      COSTFUN=COSTFUN+(HT-OBSVALUE(O))*OI*(HT-OBSVALUE(O)) !/NOBSTAT(S)
    ENDIF
  ENDDO
  COSTFUN=0.5D0*COSTFUN
! SMOOTH TERM
  CM=COSTFUN
  CALL SMOTHCOST
  CM=COSTFUN-CM
! GEOSTROPHIC BALANCE TERM
  CB=COSTFUN
  IF(IFPCDNT.EQ.0)THEN
    CALL GSBLNCOST_NON_UNIFORM_Z
  ELSEIF(IFPCDNT.EQ.1)THEN
    CALL GSBLNCOST_P_HS
  ENDIF
  CB=COSTFUN-CB
  WRITE(100,*)(CS(S),S=1,NUMSTAT),CM,CB
  RETURN
END SUBROUTINE COSTFUNCT

SUBROUTINE COSTGRADT
!*************************************************
! CALCULATE GRADIENT OF COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S,O,M,N
  INTEGER(KIND=4) :: NP(MAXDIMS)
  REAL(KIND=8)    :: HT,OI,HU,HV,DG
! --------------------
! INITIALIZATION
  DO S=1,NUMSTAT
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      GRADINT(I,J,K,T,S)=0.0
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDDO
  IF(NALLOBS.EQ.0)RETURN
  DO O=1,NALLOBS
    DO N=1,MAXDIMS
      NP(N)=OBSIDXPC(N,O)
    ENDDO
    S=OBSSTATE(O)
    OI=OBSERROR(O)**2
    OI=1.0/OI
    IF(S.LE.NUMSTAT)THEN
!   FOR CONVENTION OBSERVATION
      HT=0.0
      M=0
      DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
      DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
      DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
      DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
        M=M+1
        HT=HT+OBSCOEFF(M,O)*GRDANALS(I,J,K,T,S)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      M=0
      DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
      DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
      DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
      DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
        M=M+1
        GRADINT(I,J,K,T,S)=GRADINT(I,J,K,T,S)  &
        +(HT-OBSVALUE(O))*OI*OBSCOEFF(M,O) !/NOBSTAT(S)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ELSEIF(S.EQ.NUMSTAT+1)THEN
!   FOR RADAR OBSERVATION
      HU=0.0
      HV=0.0
      M=0
      DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
      DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
      DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
      DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
        M=M+1
        HU=HU+OBSCOEFF(M,O)*GRDANALS(I,J,K,T,S-NUMSTAT)
        HV=HV+OBSCOEFF(M,O)*GRDANALS(I,J,K,T,S-NUMSTAT+1)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      DG=OBSEINF1(O)
      HT=HU*DSIND(DG)+HV*DCOSD(DG)
      M=0
      DO T=NP(4),MIN0(NP(4)+1,NUMGRID(4))
      DO K=NP(3),MIN0(NP(3)+1,NUMGRID(3))
      DO J=NP(2),MIN0(NP(2)+1,NUMGRID(2))
      DO I=NP(1),MIN0(NP(1)+1,NUMGRID(1))
        M=M+1
        GRADINT(I,J,K,T,S-NUMSTAT  )=GRADINT(I,J,K,T,S-NUMSTAT  )  &
        +(HT-OBSVALUE(O))*OI*OBSCOEFF(M,O)*DSIND(DG) !/NOBSTAT(S)
        GRADINT(I,J,K,T,S-NUMSTAT+1)=GRADINT(I,J,K,T,S-NUMSTAT+1)  &
        +(HT-OBSVALUE(O))*OI*OBSCOEFF(M,O)*DCOSD(DG) !/NOBSTAT(S)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDIF
  ENDDO
! SMOOTH TERM
  CALL SMOTHGRAD
! GEOSTROPHIC BALANCE TERM
  IF(IFPCDNT.EQ.0)THEN
    CALL GSBLNGRAD_NON_UNIFORM_Z
  ELSEIF(IFPCDNT.EQ.1)THEN
    CALL GSBLNGRAD_P_HS
  ENDIF
  RETURN
END SUBROUTINE COSTGRADT

SUBROUTINE COAS2FINE
!*************************************************
! INTERPOLATION FROM COARSE GRID TO FINE GRID
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S,N,I0,J0,K0,T0
  INTEGER(KIND=4) :: IC(MAXDIMS)
! --------------------
  DO N=1,MAXDIMS
    NTMPGRD(N)=NUMGRID(N)
  ENDDO
  CALL TMPMEMALC
  CALL GRDMEMRLS
  DO N=1,MAXDIMS
    IC(N)=1
    IF(NTMPGRD(N).LT.MAXGRID(N))IC(N)=2
    IF(NTMPGRD(N).LT.MAXGRID(N))NUMGRID(N)=2*NUMGRID(N)-1
  ENDDO
  CALL GRDMEMALC
! GET THE GRID SPACING INFORMATION FOR NEW GRD ARRAY
  DO N=1,NUMDIMS
    IF(NTMPGRD(N).LT.MAXGRID(N))GRDSPAC(N)=GRDSPAC(N)/2.0
  ENDDO
! GET THE INFORMATION FOR NEW GRID ARRAY BY INTERPOLATION
  DO T=1,NUMGRID(4),IC(4)
  DO K=1,NUMGRID(3),IC(3)
  DO J=1,NUMGRID(2),IC(2)
  DO I=1,NUMGRID(1),IC(1)
    I0=0.5*(I+1)
    J0=0.5*(J+1)
    K0=0.5*(K+1)
    T0=0.5*(T+1)
    IF(IC(1).EQ.1)I0=I
    IF(IC(2).EQ.1)J0=J
    IF(IC(3).EQ.1)K0=K
    IF(IC(4).EQ.1)T0=T
    DO S=1,NUMSTAT
      GRDANALS(I,J,K,T,S)=TMPANALS(I0,J0,K0,T0,S)
    ENDDO
  ENDDO
  ENDDO
  ENDDO
  ENDDO
! X DIRECTION
  IF(IC(1).EQ.2)THEN
    DO T=1,NUMGRID(4)  ,IC(4)
    DO K=1,NUMGRID(3)  ,IC(3)
    DO J=1,NUMGRID(2)  ,IC(2)
    DO I=2,NUMGRID(1)-1,IC(1)
      DO S=1,NUMSTAT
        GRDANALS(I,J,K,T,S)=0.5*(GRDANALS(I-1,J,K,T,S)+GRDANALS(I+1,J,K,T,S))
      ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
! Y DIRECTION
  IF(IC(2).EQ.2)THEN
    DO T=1,NUMGRID(4)  ,IC(4)
    DO K=1,NUMGRID(3)  ,IC(3)
    DO J=2,NUMGRID(2)-1,IC(2)
    DO I=1,NUMGRID(1)
      DO S=1,NUMSTAT
        GRDANALS(I,J,K,T,S)=0.5*(GRDANALS(I,J-1,K,T,S)+GRDANALS(I,J+1,K,T,S))
      ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
! Z DIRECTION
  IF(IC(3).EQ.2)THEN
    DO T=1,NUMGRID(4)  ,IC(4)
    DO K=2,NUMGRID(3)-1,IC(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      DO S=1,NUMSTAT
        GRDANALS(I,J,K,T,S)=0.5*(GRDANALS(I,J,K-1,T,S)+GRDANALS(I,J,K+1,T,S))
      ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
! T DIRECTION
  IF(IC(4).EQ.2)THEN
    DO T=2,NUMGRID(4)-1,IC(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      DO S=1,NUMSTAT
        GRDANALS(I,J,K,T,S)=0.5*(GRDANALS(I,J,K,T-1,S)+GRDANALS(I,J,K,T+1,S))
      ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  CALL TMPMEMRLS
  RETURN
END SUBROUTINE COAS2FINE

SUBROUTINE FINE2COAS
!*************************************************
! PROJECTION FROM FINE GRID TO COARSE GRID (NOT USED)
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S,N,M,I0,J0,K0,T0
  INTEGER(KIND=4) :: IC(MAXDIMS)
! --------------------
  DO N=1,MAXDIMS
    NTMPGRD(N)=NUMGRID(N)
  ENDDO
  CALL TMPMEMALC
  CALL GRDMEMRLS
  DO N=1,MAXDIMS
    IC(N)=1
    IF(NTMPGRD(N).GT.2)IC(N)=2
    IF(NTMPGRD(N).GT.2)NUMGRID(N)=0.5*(NUMGRID(N)+1)
  ENDDO
  CALL GRDMEMALC
  DO N=1,NUMDIMS
    IF(NTMPGRD(N).GT.2)GRDSPAC(N)=GRDSPAC(N)*2.0
  ENDDO
! ----
  IF(.FALSE.)THEN
! ----
  DO T=1,NTMPGRD(4),IC(4)
  DO K=1,NTMPGRD(3),IC(3)
  DO J=1,NTMPGRD(2),IC(2)
  DO I=1,NTMPGRD(1),IC(1)
    DO S=1,NUMSTAT
      GRDANALS(I,J,K,T,S)=0.0
      M=0
      DO T0=MAX0(T-1,1),MIN0(T+1,NTMPGRD(4))
      DO K0=MAX0(K-1,1),MIN0(K+1,NTMPGRD(3))
      DO J0=MAX0(J-1,1),MIN0(J+1,NTMPGRD(2))
      DO I0=MAX0(I-1,1),MIN0(I+1,NTMPGRD(1))
        IF(I0.EQ.I.AND.J0.EQ.J.AND.K0.EQ.K.AND.T0.EQ.T)CYCLE
        M=M+1
        GRDANALS(I,J,K,T,S)=GRDANALS(I,J,K,T,S)+TMPANALS(I0,J0,K0,T0,S)
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      IF(M.GT.0)GRDANALS(I,J,K,T,S)=GRDANALS(I,J,K,T,S)/M
    ENDDO
  ENDDO
  ENDDO
  ENDDO
  ENDDO
! ----
  ELSE
! ----
  DO T=1,NTMPGRD(4),IC(4)
  DO K=1,NTMPGRD(3),IC(3)
  DO J=1,NTMPGRD(2),IC(2)
  DO I=1,NTMPGRD(1),IC(1)
    I0=0.5*(I+1)
    J0=0.5*(J+1)
    K0=0.5*(K+1)
    T0=0.5*(T+1)
    IF(IC(1).EQ.1)I0=I
    IF(IC(2).EQ.1)J0=J
    IF(IC(3).EQ.1)K0=K
    IF(IC(4).EQ.1)T0=T
    DO S=1,NUMSTAT
      GRDANALS(I0,J0,K0,T0,S)=TMPANALS(I,J,K,T,S)
    ENDDO
  ENDDO
  ENDDO
  ENDDO
  ENDDO
! ----
  ENDIF
! ----
  CALL TMPMEMRLS
  RETURN
END SUBROUTINE FINE2COAS

SUBROUTINE SMOTHCOST
!*************************************************
! SMOOTH PENALTY TERM OF COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S
  REAL(KIND=8)    :: Z1,Z2,Z3,AZ,BZ,CZ
! --------------------
! PENALTY TERM
  IF(NUMGRID(1).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=1,NUMGRID(3)
      DO J=1,NUMGRID(2)
      DO I=2,NUMGRID(1)-1
        COSTFUN=COSTFUN+PENAL_X(S)* &
        ((GRDANALS(I-1,J,K,T,S)-2*GRDANALS(I,J,K,T,S)+GRDANALS(I+1,J,K,T,S))/(GRDSPAC(1)*GRDSPAC(1)))**2
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(2).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=1,NUMGRID(3)
      DO J=2,NUMGRID(2)-1
      DO I=1,NUMGRID(1)
        COSTFUN=COSTFUN+PENAL_Y(S)* &
        ((GRDANALS(I,J-1,K,T,S)-2*GRDANALS(I,J,K,T,S)+GRDANALS(I,J+1,K,T,S))/(GRDSPAC(2)*GRDSPAC(2)))**2
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(3).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=2,NUMGRID(3)-1
      DO J=1,NUMGRID(2)
      DO I=1,NUMGRID(1)
        IF(IFPCDNT.EQ.0)THEN
          Z1=ZZZ(I,J,K-1,T)
          Z2=ZZZ(I,J,K  ,T)
          Z3=ZZZ(I,J,K+1,T)
        ELSEIF(IFPCDNT.EQ.1)THEN
          Z1=PPP(K-1)
          Z2=PPP(K  )
          Z3=PPP(K+1)
        ENDIF
        CALL G2ORDERIT(Z1,Z2,Z3,AZ,BZ,CZ)
        AZ=AZ*(Z2-Z1)*(Z3-Z2)
        BZ=BZ*(Z2-Z1)*(Z3-Z2)
        CZ=CZ*(Z2-Z1)*(Z3-Z2)
        COSTFUN=COSTFUN+PENAL_Z(S)* &
        (AZ*GRDANALS(I,J,K-1,T,S)+BZ*GRDANALS(I,J,K,T,S)+CZ*GRDANALS(I,J,K+1,T,S))**2
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(4).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=2,NUMGRID(4)-1
      DO K=1,NUMGRID(3)
      DO J=1,NUMGRID(2)
      DO I=1,NUMGRID(1)
        COSTFUN=COSTFUN+PENAL_T(S)* &
        ((GRDANALS(I,J,K,T-1,S)-2*GRDANALS(I,J,K,T,S)+GRDANALS(I,J,K,T+1,S))/(GRDSPAC(4)*GRDSPAC(4)))**2
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE SMOTHCOST

SUBROUTINE SMOTHGRAD
!*************************************************
! SMOOTH PENALTY TERM OF GRADIENT
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S
  REAL(KIND=8)    :: Z1,Z2,Z3,AZ,BZ,CZ
  REAL(KIND=8)    :: SM
! --------------------
! PENALTY TERM
  IF(NUMGRID(1).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=1,NUMGRID(3)
      DO J=1,NUMGRID(2)
      DO I=2,NUMGRID(1)-1
        SM=(GRDANALS(I-1,J,K,T,S)-2.0*GRDANALS(I,J,K,T,S)+GRDANALS(I+1,J,K,T,S))/(GRDSPAC(1)*GRDSPAC(1))
	    GRADINT(I-1,J,K,T,S)=GRADINT(I-1,J,K,T,S)+2.0*PENAL_X(S)/(GRDSPAC(1)*GRDSPAC(1))*SM
	    GRADINT(I  ,J,K,T,S)=GRADINT(I  ,J,K,T,S)+2.0*PENAL_X(S)/(GRDSPAC(1)*GRDSPAC(1))*(-2.0)*SM
	    GRADINT(I+1,J,K,T,S)=GRADINT(I+1,J,K,T,S)+2.0*PENAL_X(S)/(GRDSPAC(1)*GRDSPAC(1))*SM
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(2).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO K=1,NUMGRID(3)
      DO I=1,NUMGRID(1)
      DO J=2,NUMGRID(2)-1
        SM=(GRDANALS(I,J-1,K,T,S)-2.0*GRDANALS(I,J,K,T,S)+GRDANALS(I,J+1,K,T,S))/(GRDSPAC(2)*GRDSPAC(2))
	    GRADINT(I,J-1,K,T,S)=GRADINT(I,J-1,K,T,S)+2.0*PENAL_Y(S)/(GRDSPAC(2)*GRDSPAC(2))*SM
	    GRADINT(I,J  ,K,T,S)=GRADINT(I,J  ,K,T,S)+2.0*PENAL_Y(S)/(GRDSPAC(2)*GRDSPAC(2))*(-2.0)*SM
	    GRADINT(I,J+1,K,T,S)=GRADINT(I,J+1,K,T,S)+2.0*PENAL_Y(S)/(GRDSPAC(2)*GRDSPAC(2))*SM
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(3).GE.3)THEN
    DO S=1,NUMSTAT
      DO T=1,NUMGRID(4)
      DO J=1,NUMGRID(2)
      DO I=1,NUMGRID(1)
      DO K=2,NUMGRID(3)-1
        IF(IFPCDNT.EQ.0)THEN
          Z1=ZZZ(I,J,K-1,T)
          Z2=ZZZ(I,J,K  ,T)
          Z3=ZZZ(I,J,K+1,T)
        ELSEIF(IFPCDNT.EQ.1)THEN
          Z1=PPP(K-1)
          Z2=PPP(K  )
          Z3=PPP(K+1)
        ENDIF
        CALL G2ORDERIT(Z1,Z2,Z3,AZ,BZ,CZ)
        AZ=AZ*(Z2-Z1)*(Z3-Z2)
        BZ=BZ*(Z2-Z1)*(Z3-Z2)
        CZ=CZ*(Z2-Z1)*(Z3-Z2)
        SM=AZ*GRDANALS(I,J,K-1,T,S)+BZ*GRDANALS(I,J,K,T,S)+CZ*GRDANALS(I,J,K+1,T,S)
        GRADINT(I,J,K-1,T,S)=GRADINT(I,J,K-1,T,S)+2.0*PENAL_Z(S)*AZ*SM
        GRADINT(I,J,K  ,T,S)=GRADINT(I,J,K  ,T,S)+2.0*PENAL_Z(S)*BZ*SM
        GRADINT(I,J,K+1,T,S)=GRADINT(I,J,K+1,T,S)+2.0*PENAL_Z(S)*CZ*SM
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(4).GE.3)THEN
    DO S=1,NUMSTAT
      DO K=1,NUMGRID(3)
      DO J=1,NUMGRID(2)
      DO I=1,NUMGRID(1)
      DO T=2,NUMGRID(4)-1
        SM=(GRDANALS(I,J,K,T-1,S)-2.0*GRDANALS(I,J,K,T,S)+GRDANALS(I,J,K,T+1,S))/(GRDSPAC(4)*GRDSPAC(4))
	    GRADINT(I,J,K,T-1,S)=GRADINT(I,J,K,T-1,S)+2.0*PENAL_T(S)/(GRDSPAC(4)*GRDSPAC(4))*SM
	    GRADINT(I,J,K,T  ,S)=GRADINT(I,J,K,T  ,S)+2.0*PENAL_T(S)/(GRDSPAC(4)*GRDSPAC(4))*(-2.0)*SM
	    GRADINT(I,J,K,T+1,S)=GRADINT(I,J,K,T+1,S)+2.0*PENAL_T(S)/(GRDSPAC(4)*GRDSPAC(4))*SM
      ENDDO
      ENDDO
      ENDDO
      ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE SMOTHGRAD

SUBROUTINE GSBLNCOST_NON_UNIFORM_Z
!*************************************************
! GEOSTROPHIC BALANCE PENALTY TERM OF COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,I1,I2,J1,J2,K1,K2,K3
  REAL(KIND=8)    :: Z1,Z2,Z3,AZ,BZ,CZ
  REAL(KIND=8)    :: GS
! --------------------
  IF(PNLT0PU.LT.1.0E-10.AND.PNLT0PV.LT.1.0E-10)RETURN
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=ZZZ(I,J,K1,T)
      Z2=ZZZ(I,J,K2,T)
      Z3=ZZZ(I,J,K3,T)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=((GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
         /(XXX(I2,J)-XXX(I1,J)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J)))*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
        -((GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
         /(YYY(I,J2)-YYY(I,J1)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1)))*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
         -COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,2)+GRDBKGND(I,J,K,T,2))
      COSTFUN=COSTFUN+PNLT_PV*GS**2
    ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDIF
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=ZZZ(I,J,K1,T)
      Z2=ZZZ(I,J,K2,T)
      Z3=ZZZ(I,J,K3,T)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=((GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
         /(YYY(I,J2)-YYY(I,J1)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1)))*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
        +((GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
         /(XXX(I2,J)-XXX(I1,J)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J)))*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
         +COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,1)+GRDBKGND(I,J,K,T,1))
      COSTFUN=COSTFUN+PNLT_PU*GS**2
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GSBLNCOST_NON_UNIFORM_Z

SUBROUTINE GSBLNGRAD_NON_UNIFORM_Z
!*************************************************
! GEOSTROPHIC BALANCE PENALTY TERM OF GRADIENT
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,I1,I2,J1,J2,K1,K2,K3
  REAL(KIND=8)    :: Z1,Z2,Z3,AZ,BZ,CZ
  REAL(KIND=8)    :: GS
! --------------------
  IF(PNLT0PU.LT.1.0E-10.AND.PNLT0PV.LT.1.0E-10)RETURN
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=ZZZ(I,J,K1,T)
      Z2=ZZZ(I,J,K2,T)
      Z3=ZZZ(I,J,K3,T)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=((GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
         /(XXX(I2,J)-XXX(I1,J)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J)))*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
        -((GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
         /(YYY(I,J2)-YYY(I,J1)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1)))*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
         -COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,2)+GRDBKGND(I,J,K,T,2))
!
      GRADINT(I,J,K,T,2) =GRADINT(I,J,K,T,2) +2.0*PNLT_PV*GS*COR(I,J)*DEN(I,J,K,T)*(-1.0)
!
      GRADINT(I2,J,K,T,3)=GRADINT(I2,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I1,J,K,T,3)=GRADINT(I1,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J))*(-1.0)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         *AZ*(-1.0)*(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         *BZ*(-1.0)*(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         *CZ*(-1.0)*(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I,J2,K,T,3)=GRADINT(I,J2,K,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I,J1,K,T,3)=GRADINT(I,J1,K,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))*(-1.0)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         *AZ*(-1.0)*(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         *BZ*(-1.0)*(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         *CZ*(-1.0)*(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1))
!
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=ZZZ(I,J,K1,T)
      Z2=ZZZ(I,J,K2,T)
      Z3=ZZZ(I,J,K3,T)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=((GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
         /(YYY(I,J2)-YYY(I,J1)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1)))*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
        +((GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
         /(XXX(I2,J)-XXX(I1,J)) &
         -(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
         *(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J)))*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
         +COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,1)+GRDBKGND(I,J,K,T,1))
!
      GRADINT(I,J,K,T,1) =GRADINT(I,J,K,T,1) +2.0*PNLT_PU*GS*COR(I,J)*DEN(I,J,K,T)
!
      GRADINT(I,J2,K,T,3)=GRADINT(I,J2,K,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I,J1,K,T,3)=GRADINT(I,J1,K,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))*(-1.0)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         *AZ*(-1.0)*(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         *BZ*(-1.0)*(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         *CZ*(-1.0)*(ZZZ(I,J2,K,T)-ZZZ(I,J1,K,T))/(YYY(I,J2)-YYY(I,J1))
!
      GRADINT(I2,J,K,T,3)=GRADINT(I2,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I1,J,K,T,3)=GRADINT(I1,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J))*(-1.0)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         *AZ*(-1.0)*(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         *BZ*(-1.0)*(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J))
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         *CZ*(-1.0)*(ZZZ(I2,J,K,T)-ZZZ(I1,J,K,T))/(XXX(I2,J)-XXX(I1,J))
!
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GSBLNGRAD_NON_UNIFORM_Z

SUBROUTINE GSBLNCOST_P
!*************************************************
! GEOSTROPHIC BALANCE PENALTY TERM OF COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,I1,I2,J1,J2,K1,K2,K3
  REAL(KIND=8)    :: Z1,Z2,Z3,AZ,BZ,CZ
  REAL(KIND=8)    :: GS
! --------------------
  IF(PNLT0PU.LT.1.0E-10.AND.PNLT0PV.LT.1.0E-10)RETURN
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=PPP(K1)
      Z2=PPP(K2)
      Z3=PPP(K3)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(XXX(I2,J)-XXX(I1,J))*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
        -(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(YYY(I,J2)-YYY(I,J1))*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
        +COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,2)+GRDBKGND(I,J,K,T,2))
      COSTFUN=COSTFUN+PNLT_PV*GS**2
    ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDIF
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=PPP(K1)
      Z2=PPP(K2)
      Z3=PPP(K3)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(YYY(I,J2)-YYY(I,J1))*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
        +(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(XXX(I2,J)-XXX(I1,J))*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
        -COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,1)+GRDBKGND(I,J,K,T,1))
      COSTFUN=COSTFUN+PNLT_PU*GS**2
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GSBLNCOST_P

SUBROUTINE GSBLNGRAD_P
!*************************************************
! GEOSTROPHIC BALANCE PENALTY TERM OF GRADIENT
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,I1,I2,J1,J2,K1,K2,K3
  REAL(KIND=8)    :: Z1,Z2,Z3,AZ,BZ,CZ
  REAL(KIND=8)    :: GS
! --------------------
  IF(PNLT0PU.LT.1.0E-10.AND.PNLT0PV.LT.1.0E-10)RETURN
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=PPP(K1)
      Z2=PPP(K2)
      Z3=PPP(K3)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(XXX(I2,J)-XXX(I1,J))*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
        -(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(YYY(I,J2)-YYY(I,J1))*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
        +COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,2)+GRDBKGND(I,J,K,T,2))
!
      GRADINT(I,J,K,T,2) =GRADINT(I,J,K,T,2) +2.0*PNLT_PV*GS*COR(I,J)*DEN(I,J,K,T)
!
      GRADINT(I2,J,K,T,3)=GRADINT(I2,J,K,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
	                     /(XXX(I2,J)-XXX(I1,J)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I1,J,K,T,3)=GRADINT(I1,J,K,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*(-1.0)*DCOSD(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         *(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3) &
                          +GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3))/(XXX(I2,J)-XXX(I1,J))*AZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         *(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3) &
                          +GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3))/(XXX(I2,J)-XXX(I1,J))*BZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(2)/SCP(5)*DCOSD(DEG(I,J)) &
                         *(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3) &
                          +GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3))/(XXX(I2,J)-XXX(I1,J))*CZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J2,K,T,3)=GRADINT(I,J2,K,T,3)-2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I,J1,K,T,3)=GRADINT(I,J1,K,T,3)-2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*(-1.0)*DSIND(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)-2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         *(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3) &
                          +GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3))/(YYY(I,J2)-YYY(I,J1))*AZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)-2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         *(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3) &
                          +GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3))/(YYY(I,J2)-YYY(I,J1))*BZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)-2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(2)/SCP(5)*DSIND(DEG(I,J)) &
                         *(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3) &
                          +GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3))/(YYY(I,J2)-YYY(I,J1))*CZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      K1=MAX0(K-1 ,1)
      K1=MIN0(K1  ,NUMGRID(3)-2)
      K2=MIN0(K1+1,NUMGRID(3)-1)
      K3=MIN0(K2+1,NUMGRID(3))
      Z1=PPP(K1)
      Z2=PPP(K2)
      Z3=PPP(K3)
      IF(K.EQ.1)CALL GDERIVELB(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.GE.2.AND.K.LE.NUMGRID(3)-1)CALL GDERIVEIT(Z1,Z2,Z3,AZ,BZ,CZ)
      IF(K.EQ.NUMGRID(3))CALL GDERIVERB(Z1,Z2,Z3,AZ,BZ,CZ)
      GS=(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(YYY(I,J2)-YYY(I,J1))*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
        +(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
         +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ) &
        /(XXX(I2,J)-XXX(I1,J))*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
        -COR(I,J)*DEN(I,J,K,T)*(GRDANALS(I,J,K,T,1)+GRDBKGND(I,J,K,T,1))
!
      GRADINT(I,J,K,T,1) =GRADINT(I,J,K,T,1) +2.0*PNLT_PU*GS*COR(I,J)*DEN(I,J,K,T)*(-1.0)
!
      GRADINT(I,J2,K,T,3)=GRADINT(I,J2,K,T,3)+2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I,J1,K,T,3)=GRADINT(I,J1,K,T,3)+2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*(-1.0)*DCOSD(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)+2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         *(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3) &
                          +GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3))/(YYY(I,J2)-YYY(I,J1))*AZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)+2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         *(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3) &
                          +GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3))/(YYY(I,J2)-YYY(I,J1))*BZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)+2.0*PNLT_PU*GS*SCP(3)/SCP(2)/SCP(4)/SCL(1)/SCP(5)*DCOSD(DEG(I,J)) &
                         *(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3) &
                          +GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3))/(YYY(I,J2)-YYY(I,J1))*CZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I2,J,K,T,3)=GRADINT(I2,J,K,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
	                     /(XXX(I2,J)-XXX(I1,J)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I1,J,K,T,3)=GRADINT(I1,J,K,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*(-1.0)*DSIND(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J)) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)
!
      GRADINT(I,J,K1,T,3)=GRADINT(I,J,K1,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         *(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3) &
                          +GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3))/(XXX(I2,J)-XXX(I1,J))*AZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K2,T,3)=GRADINT(I,J,K2,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         *(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3) &
                          +GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3))/(XXX(I2,J)-XXX(I1,J))*BZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
      GRADINT(I,J,K3,T,3)=GRADINT(I,J,K3,T,3)+2.0*PNLT_PV*GS*SCP(3)/SCP(1)/SCP(4)/SCL(1)/SCP(5)*DSIND(DEG(I,J)) &
                         *(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3) &
                          +GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3))/(XXX(I2,J)-XXX(I1,J))*CZ*(-1.0) &
                         /(GRDANALS(I,J,K1,T,3)*AZ+GRDANALS(I,J,K2,T,3)*BZ+GRDANALS(I,J,K3,T,3)*CZ &
                          +GRDBKGND(I,J,K1,T,3)*AZ+GRDBKGND(I,J,K2,T,3)*BZ+GRDBKGND(I,J,K3,T,3)*CZ)**2
!
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GSBLNGRAD_P

SUBROUTINE GSBLNCOST_P_HS
!*************************************************
! GEOSTROPHIC BALANCE PENALTY TERM OF COST FUNCTION
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  REAL(KIND=8),PARAMETER :: GA=9.8D0
  INTEGER(KIND=4) :: I,J,K,T,I1,I2,J1,J2
  REAL(KIND=8)    :: GS
! --------------------
  IF(PNLT0PU.LT.1.0E-10.AND.PNLT0PV.LT.1.0E-10)RETURN
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      GS=(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(XXX(I2,J)-XXX(I1,J))*SCL(3)/SCP(1)/SCP(4)/SCL(2)*GA*DCOSD(DEG(I,J)) &
        -(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(YYY(I,J2)-YYY(I,J1))*SCL(3)/SCP(2)/SCP(4)/SCL(2)*GA*DSIND(DEG(I,J)) &
        -COR(I,J)*(GRDANALS(I,J,K,T,2)+GRDBKGND(I,J,K,T,2))
      COSTFUN=COSTFUN+PNLT_PV*GS**2
    ENDDO
    ENDDO
    ENDDO
    ENDDO
    ENDIF
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      GS=(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(YYY(I,J2)-YYY(I,J1))*SCL(3)/SCP(2)/SCP(4)/SCL(1)*GA*DCOSD(DEG(I,J)) &
        +(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(XXX(I2,J)-XXX(I1,J))*SCL(3)/SCP(1)/SCP(4)/SCL(1)*GA*DSIND(DEG(I,J)) &
        +COR(I,J)*(GRDANALS(I,J,K,T,1)+GRDBKGND(I,J,K,T,1))
      COSTFUN=COSTFUN+PNLT_PU*GS**2
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GSBLNCOST_P_HS

SUBROUTINE GSBLNGRAD_P_HS
!*************************************************
! GEOSTROPHIC BALANCE PENALTY TERM OF GRADIENT
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  REAL(KIND=8),PARAMETER :: GA=9.8D0
  INTEGER(KIND=4) :: I,J,K,T,I1,I2,J1,J2
  REAL(KIND=8)    :: GS
! --------------------
  IF(PNLT0PU.LT.1.0E-10.AND.PNLT0PV.LT.1.0E-10)RETURN
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      GS=(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(XXX(I2,J)-XXX(I1,J))*SCL(3)/SCP(1)/SCP(4)/SCL(2)*GA*DCOSD(DEG(I,J)) &
        -(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(YYY(I,J2)-YYY(I,J1))*SCL(3)/SCP(2)/SCP(4)/SCL(2)*GA*DSIND(DEG(I,J)) &
        -COR(I,J)*(GRDANALS(I,J,K,T,2)+GRDBKGND(I,J,K,T,2))
!
      GRADINT(I,J,K,T,2) =GRADINT(I,J,K,T,2) +2.0*PNLT_PV*GS*COR(I,J)*(-1.0)
!
      GRADINT(I2,J,K,T,3)=GRADINT(I2,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)*DCOSD(DEG(I,J)) &
	                     /(XXX(I2,J)-XXX(I1,J))*GA
!
      GRADINT(I1,J,K,T,3)=GRADINT(I1,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(2)*(-1.0)*DCOSD(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J))*GA
!
      GRADINT(I,J2,K,T,3)=GRADINT(I,J2,K,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)*DSIND(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))*GA
!
      GRADINT(I,J1,K,T,3)=GRADINT(I,J1,K,T,3)-2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(2)*(-1.0)*DSIND(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))*GA
!
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  IF(NUMGRID(1).GE.2.AND.NUMGRID(2).GE.2.AND.NUMGRID(3).GE.3.AND.NUMSTAT.GE.3)THEN
    DO T=1,NUMGRID(4)
    DO K=1,NUMGRID(3)
    DO J=1,NUMGRID(2)
    DO I=1,NUMGRID(1)
      I1=MAX0(I-1,1)
      I2=MIN0(I+1,NUMGRID(1))
      J1=MAX0(J-1,1)
      J2=MIN0(J+1,NUMGRID(2))
      GS=(GRDANALS(I,J2,K,T,3)-GRDANALS(I,J1,K,T,3)+GRDBKGND(I,J2,K,T,3)-GRDBKGND(I,J1,K,T,3)) &
        /(YYY(I,J2)-YYY(I,J1))*SCL(3)/SCP(2)/SCP(4)/SCL(1)*GA*DCOSD(DEG(I,J)) &
        +(GRDANALS(I2,J,K,T,3)-GRDANALS(I1,J,K,T,3)+GRDBKGND(I2,J,K,T,3)-GRDBKGND(I1,J,K,T,3)) &
        /(XXX(I2,J)-XXX(I1,J))*SCL(3)/SCP(1)/SCP(4)/SCL(1)*GA*DSIND(DEG(I,J)) &
        +COR(I,J)*(GRDANALS(I,J,K,T,1)+GRDBKGND(I,J,K,T,1))
!
      GRADINT(I,J,K,T,1) =GRADINT(I,J,K,T,1) +2.0*PNLT_PU*GS*COR(I,J)
!
      GRADINT(I,J2,K,T,3)=GRADINT(I,J2,K,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)*DCOSD(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))*GA
!
      GRADINT(I,J1,K,T,3)=GRADINT(I,J1,K,T,3)+2.0*PNLT_PU*GS*SCL(3)/SCP(2)/SCP(4)/SCL(1)*(-1.0)*DCOSD(DEG(I,J)) &
                         /(YYY(I,J2)-YYY(I,J1))*GA
!
      GRADINT(I2,J,K,T,3)=GRADINT(I2,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)*DSIND(DEG(I,J)) &
	                     /(XXX(I2,J)-XXX(I1,J))*GA
!
      GRADINT(I1,J,K,T,3)=GRADINT(I1,J,K,T,3)+2.0*PNLT_PV*GS*SCL(3)/SCP(1)/SCP(4)/SCL(1)*(-1.0)*DSIND(DEG(I,J)) &
                         /(XXX(I2,J)-XXX(I1,J))*GA
!
    ENDDO
    ENDDO
    ENDDO
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GSBLNGRAD_P_HS

SUBROUTINE CHECK_F_G
!*************************************************
! CHECK WHETHER THE GRADIENT MATCH COST FUNCTION (AFFILIATE)
! HISTORY: AUGUST 2007, CODED by WEI LI.
!*************************************************
  IMPLICIT NONE
! --------------------
  INTEGER(KIND=4) :: I,J,K,T,S
  REAL(KIND=8)    :: CONTROL(NUMGRID(1),NUMGRID(2),NUMGRID(3),NUMGRID(4),NUMSTAT)
  REAL(KIND=8)    :: ED,F2,F1,GG
! --------------------
  ED=0.00001
  DO S=1,NUMSTAT
  DO T=1,NUMGRID(4)
  DO K=1,NUMGRID(3)
  DO J=1,NUMGRID(2)
  DO I=1,NUMGRID(1)
    CONTROL(I,J,K,T,S)=GRDANALS(I,J,K,T,S)
  ENDDO
  ENDDO
  ENDDO
  ENDDO
  ENDDO
  CALL COSTGRADT
  DO S=1,NUMSTAT
  DO T=1,NUMGRID(4)
  DO K=1,NUMGRID(3)
  DO J=1,NUMGRID(2)
  DO I=1,NUMGRID(1)
    PRINT*,'       '
    PRINT*,'       '
    PRINT*,'       '
    PRINT*,'       '
    PRINT*,'       '
    GRDANALS(I,J,K,T,S)=CONTROL(I,J,K,T,S)+ED
    CALL COSTFUNCT
    F2=COSTFUN
    GRDANALS(I,J,K,T,S)=CONTROL(I,J,K,T,S)-ED
    CALL COSTFUNCT
    F1=COSTFUN
    GRDANALS(I,J,K,T,S)=CONTROL(I,J,K,T,S)
    GG=(F2-F1)/(2.0*ED)
!    PRINT*,F2,F1,GG
	IF(DABS(GRADINT(I,J,K,T,S)-GG).GT.1.0E-19) &
    PRINT*,I,J,K,T,S,GRADINT(I,J,K,T,S),GG,GRADINT(I,J,K,T,S)-GG
	IF(DABS(GRADINT(I,J,K,T,S)-GG).GT.1000.0)STOP
  ENDDO
  ENDDO
  ENDDO
  ENDDO
  ENDDO
  RETURN
END SUBROUTINE CHECK_F_G

END MODULE STMAS4D_CORE
