#! /bin/csh

set verbose=1

set rStatus = 130
set fN=cpuCount.`date +%s`.$$
touch /tmp/$fN

onintr cleanup

set runPrefix = `echo $0 | cut -c1-1`
switch ($runPrefix)
  case /:
  case .:
        set runScript = $0
        breaksw
  default:
        set runScript = `which $0`
        breaksw
endsw
set baseDir = `dirname $runScript`

$baseDir/qsub $* >& /tmp/$fN

set rStatus = $status

if ( $rStatus == 0) then
  set noglob
  set jobID=`cat /tmp/$fN | sed -e 's/[yY]our job //' | sed -e 's/ (.*//' | awk /[0-9][0-9]*/`
  unset noglob
  if ( x$jobID == x ) then
    set rStatus = 1
    cat /tmp/$fN
    echo QSUB Failed.
  else
    cat /tmp/$fN
    echo Waiting...
    $baseDir/wait_job $jobID
    set rStatus = $status
  endif
else
  cat /tmp/$fN
  echo QSUB Failed.
endif

cleanup:
  rm -f /tmp/$fN
