SUBROUTINE LAPS_INGEST

!==============================================================================
!doc  THIS ROUTINE INGESTS OBSERVATION DATA BY LAPS LIBRARIES.
!doc
!doc  HISTORY:
!doc	CREATION:	YUANFU XIE	MAY 2007
!==============================================================================

  IMPLICIT NONE

  ! PROFILER:
  CALL CONV_PROFLR

  ! SONDE:
  CALL CONV_SONDES

  ! SURFACE OBS:
  CALL CONV_SFCOBS

  ! CDW AND ACARS:
  CALL CONV_CDWACA

END SUBROUTINE LAPS_INGEST

SUBROUTINE CONV_PROFLR

!==============================================================================
!doc  THIS ROUTINE READS AND CONVERTS PROFILER OBSERVATION DATA INTO DATA FORMAT
!doc  REQUESTED.
!doc
!doc  HISTORY:
!doc	CREATION:	YUANFU XIE	JUN 2007
!==============================================================================

  USE LAPS_PARAMS

  IMPLICIT NONE

  CHARACTER :: FSPECS*225, EXTNSN*31,C5NAME(MAXNUM_PROFLRS)*5, &
               OBTYPE(MAXNUM_PROFLRS)*8
  INTEGER   :: IOFILE,STATUS,NPRFLR,NLEVEL(MAXNUM_PROFLRS)
  INTEGER   :: I4TIME,OBTIME(MAXNUM_PROFLRS)
  REAL	    :: PRFLAT(MAXNUM_PROFLRS),PRFLON(MAXNUM_PROFLRS),&
               PRFELV(MAXNUM_PROFLRS)
  REAL      :: HGHTOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! HEIGHT OBS
  REAL      :: UWNDOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! U WIND OBS
  REAL      :: VWNDOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! V WIND OBS
  REAL      :: RMSOBS(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! RMS
  REAL      :: TSFCOB(MAXNUM_PROFLRS)			! SFC T OBS
  REAL      :: PSFCOB(MAXNUM_PROFLRS)			! SFC P OBS
  REAL      :: RHSFCO(MAXNUM_PROFLRS)			! SFC RH OBS
  REAL      :: USFCOB(MAXNUM_PROFLRS)			! SFC U OBS
  REAL      :: VSFCOB(MAXNUM_PROFLRS)			! SFC V OBS

  IOFILE = 12
  NLEVEL = 0

  ! OPEN NEAREST PROFILER FILE TO THE LAPS ANALYSIS TIME:
  EXTNSN = 'pro'
  CALL GET_FILESPEC(EXTNSN,2,FSPECS,STATUS)

  CALL GET_FILE_TIME(FSPECS,SYSTEM_IN4TIME,I4TIME)

  ! CHECK IF DATA FILE IS CLOSE TO SYSTEM TIME:
  IF (ABS(SYSTEM_IN4TIME-I4TIME) .GT. LENGTH_ANATIME) THEN
    PRINT*,'CONV_PROFLR: No recent profiler data files'
    RETURN
  ENDIF

  ! READ PROFILER DATA:
  CALL READ_PRO_DATA(IOFILE,I4TIME,EXTNSN,MAXNUM_PROFLRS,MAXLVL_PROFLRS, & ! I
                     NPRFLR,NLEVEL,PRFLAT,PRFLON,PRFELV,C5NAME,OBTIME,   & ! O
                     OBTYPE,HGHTOB,UWNDOB,VWNDOB,RMSOBS,TSFCOB,PSFCOB,   & ! O
                     RHSFCO,USFCOB,VSFCOB,STATUS)                          ! O
  CALL LAPS_DIVIDER
  WRITE(6,*) 'CONV_PROFLR: Number of profilers data read: ',NPRFLR
  CALL LAPS_DIVIDER

  ! CONVERT TO THE REQUESTED FORMAT:
  IF (NPRFLR .GT. 0) THEN
    WRITE(6,*) 'CONV_PROFLR: Levels at each profiler: ',NLEVEL(1:NPRFLR)
    IF      (FORMAT_REQUEST .EQ. 'BUFR') THEN
      CALL BUFR_PROFLR(NPRFLR,NLEVEL,C5NAME,OBTIME,PRFLAT,PRFLON,PRFELV, &
                       OBTYPE,MAXNUM_PROFLRS,HGHTOB,UWNDOB,VWNDOB,RMSOBS, &
                       PSFCOB,TSFCOB,RHSFCO,USFCOB,VSFCOB)
    ELSE IF (FORMAT_REQUEST .NE. 'WRF') THEN
      CALL WRFD_PROFLR(NPRFLR,NLEVEL,C5NAME,OBTIME,PRFLAT,PRFLON,PRFELV, &
                       OBTYPE,MAXNUM_PROFLRS,HGHTOB,UWNDOB,VWNDOB,PSFCOB, &
                       TSFCOB,RHSFCO,USFCOB,VSFCOB)
    ENDIF
  ENDIF

END SUBROUTINE CONV_PROFLR


SUBROUTINE CONV_SONDES

!==============================================================================
!  THIS ROUTINE READS AND CONVERTS SONDING OBSERVATION DATA INTO DATA FORMAT
!  REQUESTED.
!
!  HISTORY:
!	CREATION:	YUANFU XIE	JUN 2007
!==============================================================================

  USE LAPS_PARAMS

  IMPLICIT NONE

  CHARACTER :: FSPECS*225, EXTNSN*3,C5NAME(MAXNUM_PROFLRS)*5, &
               OBTYPE(MAXNUM_PROFLRS)*8
  INTEGER   :: IOFILE,STATUS,NPRFLR,NLEVEL(MAXNUM_PROFLRS), &
               WINDOW,MODEOB
  INTEGER   :: I4TIME,PRFTIM(MAXNUM_PROFLRS,MAXLVL_PROFLRS)
  REAL	    :: PRFLAT(MAXNUM_PROFLRS,MAXLVL_PROFLRS), &
               PRFLON(MAXNUM_PROFLRS,MAXLVL_PROFLRS), &
               PRFELV(MAXNUM_PROFLRS)
  REAL      :: HGHTOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! HEIGHT OBS
  REAL      :: PRSOBS(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! PRESSURE OBS
  REAL      :: UWNDOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! U WIND OBS
  REAL      :: VWNDOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! V WIND OBS
  REAL      :: TEMPOB(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! T OBS
  REAL      :: DEWOBS(MAXNUM_PROFLRS,MAXLVL_PROFLRS)	! DEW POINT OBS

  IOFILE = 12
  NLEVEL = 0
  WINDOW = 0			! I4TIME WINDOW MIMIC READ_PROFILES.F
  MODEOB = 3			! KEY LEVELS OFF OF WIND DATA

  ! OPEN NEAREST PROFILER FILE TO THE LAPS ANALYSIS TIME:
  EXTNSN = 'snd'
  CALL GET_FILESPEC(EXTNSN,2,FSPECS,STATUS)

  CALL GET_FILE_TIME(FSPECS,SYSTEM_IN4TIME,I4TIME)
  IF (ABS(SYSTEM_IN4TIME-I4TIME) .GT. LENGTH_ANATIME) THEN
    WRITE(6,*) 'CONV_SONDES: Warning: nearest sonde file is outside window'
  ELSE

    ! READ SONDE DATA:
    CALL READ_SND_DATA2(IOFILE,I4TIME,EXTNSN,MAXNUM_PROFLRS,MAXLVL_PROFLRS, & ! I
                       DOMAIN_LATITDE,DOMAIN_LONGITD,NUMBER_GRIDPTS(1),     & ! I
                       NUMBER_GRIDPTS(2),NUMBER_GRIDPTS(3),HEIGHT_GRID3DM,  & ! I
                       .TRUE.,MODEOB,                                       & ! I
                       NPRFLR,PRFELV,NLEVEL,C5NAME,OBTYPE,HGHTOB,           & ! O
                       PRSOBS,UWNDOB,VWNDOB,TEMPOB,DEWOBS,PRFLAT,PRFLON,    & ! O
                       PRFTIM,STATUS)                                         ! O
    CALL LAPS_DIVIDER
    WRITE(6,*) 'CONV_SONDES: Number of sonde data read: ',NPRFLR
    CALL LAPS_DIVIDER

    ! CONVERT TO THE REQUESTED FORMAT:
    IF (NPRFLR .GT. 0) THEN
      WRITE(6,*) 'CONV_SONDES: Levels at each sonde: ',NLEVEL(1:NPRFLR)
      IF      (FORMAT_REQUEST .EQ. 'BUFR') THEN
        CALL BUFR_SONDES(NPRFLR,NLEVEL,C5NAME,PRFTIM,PRFLAT,PRFLON,PRFELV, &
                         OBTYPE,HGHTOB,PRSOBS,TEMPOB,DEWOBS,UWNDOB,VWNDOB)
      ELSE IF (FORMAT_REQUEST .NE. 'WRF') THEN
        CALL WRFD_SONDES(NPRFLR,NLEVEL,C5NAME,PRFTIM,PRFLAT,PRFLON,PRFELV, &
                         OBTYPE,HGHTOB,PRSOBS,TEMPOB,DEWOBS,UWNDOB,VWNDOB)
      ENDIF
    ENDIF

  ENDIF

END SUBROUTINE CONV_SONDES

SUBROUTINE CONV_SFCOBS

!==============================================================================
!  THIS ROUTINE READS AND CONVERTS SURFACE OBSERVATIONS INTO REQUESTED DATA
!  FORMAT.
!
!  HISTORY:
!	CREATION:	YUANFU XIE	JUN 2007
!==============================================================================

  USE LAPS_PARAMS

  IMPLICIT NONE

  CHARACTER*24 :: FILETM		! OBS FILE TIME
  INTEGER :: MAXSTN,STATUS,I		! MAXIMUM STATIONS
  INTEGER :: NOBGRD,NOBBOX		! NUMBER OF OBS OVER GRID AND BOX

  CHARACTER*20,ALLOCATABLE,DIMENSION(:) :: STNAME	! STATION NAMES
  CHARACTER*11,ALLOCATABLE,DIMENSION(:) :: PVNAME	! PROVIDER NAMES
  CHARACTER*25,ALLOCATABLE,DIMENSION(:) :: PRSTWX	! PRESENT WEATHER
  CHARACTER*6, ALLOCATABLE,DIMENSION(:) :: RPTYPE	! REPORT TYPE
  CHARACTER*6, ALLOCATABLE,DIMENSION(:) :: STNTYP	! STATION TYPE
  INTEGER,     ALLOCATABLE,DIMENSION(:) :: OBTIME,WMOIDS! OBS TIME/WMO ID
  INTEGER,     ALLOCATABLE,DIMENSION(:) :: CLDLYR,PRSCHC! CLOUD LAYER/PRS CHG
  REAL,        ALLOCATABLE,DIMENSION(:) :: &
    OBSLAT,OBSLON,OBSELV,OBSTMP,ERRTMP,OBSDEW,ERRDEW,OBSRHS,ERRRHS, &
    OBSDIR,ERRDIR,OBSSPD,ERRSPD,GUSDIR,GUSSPD,OBSALT,ERRALT,STNPRS, &
    MSLPRS,PRSCH3,ERRPRS,OBSVIS,ERRVIS,OBSSOL,ERRSOL,SFCTMP,ERRSFT, &
    SFCMOI,ERRSFM,PRECP1,PRECP3,PRECP6,PREC24,ERRPCP,SNOWCV,ERRSNW, &
    MAXTMP,MINTMP,igrid,jgrid

  CHARACTER*4, ALLOCATABLE,DIMENSION(:,:) :: CLDAMT     ! CLOUD AMOUNT

  REAL,        ALLOCATABLE,DIMENSION(:,:) :: CLDHGT	! CLOUD HEIGHTS
  REAL,        ALLOCATABLE,DIMENSION(:,:) :: OBSWND, &  ! OBS WIND
                                             ERRWND	! OBS WIND ERROR

  ! GET MAXIMUM NUMBER OF SURFACE STATIONS:
  CALL GET_MAXSTNS(MAXSTN,STATUS)
  IF (STATUS .NE. 1) THEN
    WRITE(6,*) 'CONV_SONDES: ERROR IN READING MAXIMUM SFC STATIONS'
    STOP
  ENDIF

  ! ALLOCATABLE MEMORY FOR SURFACE VARIABLES:
  ALLOCATE(OBTIME(MAXSTN),WMOIDS(MAXSTN),STNAME(MAXSTN), &
           PVNAME(MAXSTN),PRSTWX(MAXSTN),RPTYPE(MAXSTN), &
           STNTYP(MAXSTN),OBSLAT(MAXSTN),OBSLON(MAXSTN), &
           OBSELV(MAXSTN),OBSTMP(MAXSTN),OBSDEW(MAXSTN), &
           OBSRHS(MAXSTN),OBSDIR(MAXSTN),OBSSPD(MAXSTN), &
           GUSDIR(MAXSTN),GUSSPD(MAXSTN),OBSALT(MAXSTN), &
           STNPRS(MAXSTN),MSLPRS(MAXSTN),PRSCHC(MAXSTN), &
           PRSCH3(MAXSTN),OBSVIS(MAXSTN),OBSSOL(MAXSTN), &
           SFCTMP(MAXSTN),SFCMOI(MAXSTN),PRECP1(MAXSTN), &
           PRECP3(MAXSTN),PRECP6(MAXSTN),PREC24(MAXSTN), &
           SNOWCV(MAXSTN),CLDLYR(MAXSTN),MAXTMP(MAXSTN), &
           MINTMP(MAXSTN),ERRTMP(MAXSTN),ERRDEW(MAXSTN), &
           ERRRHS(MAXSTN),ERRDIR(MAXSTN),ERRSPD(MAXSTN), &
           ERRALT(MAXSTN),ERRPRS(MAXSTN),ERRVIS(MAXSTN), &
           ERRSOL(MAXSTN),ERRSFT(MAXSTN),ERRSFM(MAXSTN), &
           ERRPCP(MAXSTN),ERRSNW(MAXSTN), igrid(maxstn),jgrid(maxstn), &
           CLDAMT(MAXSTN,5),CLDHGT(MAXSTN,5), &
           OBSWND(2,MAXSTN),ERRWND(2,MAXSTN), STAT=STATUS)
  IF (STATUS .NE. 0) THEN
    WRITE(6,*) 'CONV_SFCOBS: ERROR IN ALLOCATING MEMORY FOR SURFACE DATA'
    STOP
  ENDIF

  ! READ SFC OBS:
  CALL READ_SURFACE_DATA(SYSTEM_IN4TIME,FILETM,NOBGRD,NOBBOX,OBTIME,WMOIDS,&
                         STNAME,PVNAME,PRSTWX,RPTYPE,STNTYP,OBSLAT,OBSLON, &
                         OBSELV,OBSTMP,OBSDEW,OBSRHS,OBSDIR,OBSSPD,GUSDIR, &
                         GUSSPD,OBSALT,STNPRS,MSLPRS,PRSCHC,PRSCH3,OBSVIS, &
                         OBSSOL,SFCTMP,SFCMOI,PRECP1,PRECP3,PRECP6,PREC24, &
                         SNOWCV,CLDLYR,MAXTMP,MINTMP,                             &
                         ERRTMP,ERRDEW,ERRRHS,ERRDIR,ERRSPD,ERRALT,ERRPRS, &
                         ERRVIS,ERRSOL,ERRSFT,ERRSFM,ERRPCP,ERRSNW,CLDAMT, &
                         CLDHGT,MAXSTN,STATUS)

  IF (STATUS .NE. 1) THEN
    WRITE(6,*) 'CONV_SFCOBS: ERROR IN READING SURFACE OBS'
    STOP
  ENDIF

  ! CONVERT WIND DIRECTION AND SPEED INTO U AND V:
  DO I=1,NOBBOX
    call latlon_to_rlapsgrid(obslat(I),obslon(I),DOMAIN_LATITDE,DOMAIN_LONGITD, &
				NUMBER_GRIDPTS(1),NUMBER_GRIDPTS(2),igrid(i),jgrid(i),status)
    IF ((OBSDIR(I) .NE. RVALUE_MISSING) .AND. &
        (OBSDIR(I) .NE. SFCOBS_INVALID) .AND. &
        (OBSSPD(I) .NE. RVALUE_MISSING) .AND. &
        (OBSSPD(I) .NE. SFCOBS_INVALID)) THEN
      CALL DISP_TO_UV(OBSDIR(I),OBSSPD(I),OBSWND(1,I),OBSWND(2,I))
      CALL DISP_TO_UV(ERRDIR(I),ERRSPD(I),ERRWND(1,I),ERRWND(2,I))
    ELSE
      OBSWND(1:2,I) = RVALUE_MISSING
      ERRWND(1:2,I) = RVALUE_MISSING
    ENDIF
  ENDDO

  CALL LAPS_DIVIDER
  WRITE(6,*) 'CONV_SFCOBS: Number of surface obs data read: ',NOBBOX,NOBGRD
  CALL LAPS_DIVIDER

  ! CONVERT TO THE REQUESTED DATA FORMAT:
  IF      (FORMAT_REQUEST .EQ. 'BUFR') THEN
    CALL BUFR_SFCOBS(NOBBOX,OBTIME, &
                     OBSLAT,OBSLON,STNAME,RPTYPE,PVNAME,OBSELV, &
                     MSLPRS,ERRPRS,STNPRS,ERRPRS,OBSTMP,ERRTMP, &
                     OBSWND,ERRWND,OBSRHS,ERRRHS,STNPRS,PRECP1,ERRPCP)
  ELSE IF (FORMAT_REQUEST .EQ. 'WRF' ) THEN
    CALL WRFD_SFCOBS(NOBBOX,OBTIME, &
                     OBSLAT,OBSLON,STNAME,RPTYPE,PVNAME,OBSELV, &
                     MSLPRS,ERRPRS,STNPRS,ERRPRS,OBSTMP,ERRTMP, &
                     OBSWND,ERRWND,OBSRHS,ERRRHS,STNPRS,PRECP1,ERRPCP)
  ENDIF

  ! DEALLOCATABLE MEMORY FOR SURFACE VARIABLES:
  DEALLOCATE(OBTIME,WMOIDS,STNAME, &
             PVNAME,PRSTWX,RPTYPE, &
             STNTYP,OBSLAT,OBSLON, &
             OBSELV,OBSTMP,OBSDEW, &
             OBSRHS,OBSDIR,OBSSPD, &
             GUSDIR,GUSSPD,OBSALT, &
             STNPRS,MSLPRS,PRSCHC, &
             PRSCH3,OBSVIS,OBSSOL, &
             SFCTMP,SFCMOI,PRECP1, &
             PRECP3,PRECP6,PREC24, &
             SNOWCV,CLDLYR,MAXTMP, &
             MINTMP,ERRTMP,ERRDEW, &
             ERRRHS,ERRDIR,ERRSPD, &
             ERRALT,ERRPRS,ERRVIS, &
             ERRSOL,ERRSFT,ERRSFM, &
             ERRPCP,ERRSNW, &
             CLDAMT,CLDHGT, &
             OBSWND,ERRWND, STAT=STATUS)
  IF (STATUS .NE. 0) THEN
    WRITE(6,*) 'CONV_SFCOBS: ERROR IN DEALLOCATING MEMORY FOR SURFACE OBS'
    STOP
  ENDIF

END SUBROUTINE CONV_SFCOBS

SUBROUTINE CONV_CDWACA

!==============================================================================
!  THIS ROUTINE READS AND CONVERTS CLOUD DRIFT WIND AND ACARS (PIREP) DATA INTO
!  REQUESTED DATA FORMAT
!
!  HISTORY:
!	CREATION:	YUANFU XIE	JUN 2007
!==============================================================================

  USE LAPS_PARAMS

  IMPLICIT NONE

  ! LOCAL VARIABLES:
  INTEGER, PARAMETER :: MAXOBS=5000	! LOCALLY DEFINED,CHANGE IT IF NEEDED
  CHARACTER :: EXTEND*3,OBSTYP*4,ASCTIM*9
  INTEGER   :: NUMOBS,STATUS
  INTEGER   :: OBSINT(3,MAXOBS)
  REAL      :: OBSLAT,OBSLON,OBSELV,OBSPRS,OBSDIR,OBSSPD,OBSTMP,OBSNON
  REAL*8    :: OBARRY(7,MAXOBS)

  ! CLOUD DRIFT WIND:
  NUMOBS = 0
  EXTEND = 'cdw'
  CALL OPEN_LAPSPRD_FILE_READ(POINTS_CHANNEL,SYSTEM_IN4TIME,EXTEND,STATUS)
  IF (STATUS .NE. 1) THEN
    PRINT*,'CONV_CDWACA: No cloud drift wind data'
  ELSE
    STATUS = 0
    DO
      CALL READ_LAPS_CDW_WIND(POINTS_CHANNEL,OBSLAT,OBSLON,OBSPRS,OBSDIR,OBSSPD, &
                               ASCTIM,STATUS)
      IF (STATUS .NE. 0) EXIT
      NUMOBS = NUMOBS+1
      PRINT*,'CONV_CDWACA: FOUND CDW DATA, COMPLETE THIS CODE'
      STOP
      OBSINT(1,NUMOBS) = 63		! USE BUFR REPORT TYPE CODE: 
                                        ! 63 SATELLITE DERIVED WIND
      OBSINT(2,NUMOBS) = 241		! RERORT TYPE: SATWIND
      CALL CV_ASC_I4TIME(ASCTIM,OBSINT(3,NUMOBS))
      PRINT*,'CDW: ',OBSLAT,OBSLON,OBSPRS,OBSDIR,OBSSPD,OBSINT(3,NUMOBS)
    ENDDO
  ENDIF
  CLOSE(POINTS_CHANNEL)
  PRINT*,'CONV_CDWACA: Total of CDW OBS: ',NUMOBS
  IF (NUMOBS .GT. MAXOBS) THEN
    PRINT*,'CONV_CDW_ACA: Data array is too small, MAXOBS needs enlarge ',NUMOBS,MAXOBS
    STOP
  ENDIF

  ! ACAR (PIREP):
  EXTEND = 'pin'

  ! 1. TEMP:
  OBSTYP = 'temp'
  CALL OPEN_LAPSPRD_FILE_READ(POINTS_CHANNEL,SYSTEM_IN4TIME,EXTEND,STATUS)
  IF (STATUS .NE. 1) THEN
    PRINT*,'CONV_CDWACA: No ACAR (PIREP) temp data'
  ELSE
    STATUS = 0
    DO
      CALL READ_ACARS_OB(POINTS_CHANNEL,OBSTYP,OBSLAT,OBSLON,OBSELV,OBSTMP,OBSNON, &
                               ASCTIM,0,STATUS)
      IF (STATUS .NE. 0) EXIT
      NUMOBS = NUMOBS+1
      OBARRY(1:7,NUMOBS) = RVALUE_MISSING
      OBARRY(1,NUMOBS) = OBSLAT
      OBARRY(2,NUMOBS) = OBSLON
      OBARRY(3,NUMOBS) = OBSELV
      OBARRY(7,NUMOBS) = OBSTMP
      OBSINT(1,NUMOBS) = 41		! USE BUFR REPORT TYPE CODE: 
                                        ! 41 ACARS TEMPERATURE
      OBSINT(2,NUMOBS) = 130		! PILOR REPORT: TEMPERATURE
      CALL CV_ASC_I4TIME(ASCTIM,OBSINT(3,NUMOBS))
      PRINT*,'ACAR TEMP: ',OBSLAT,OBSLON,OBSELV,OBSTMP,OBSINT(3,NUMOBS)
    ENDDO
  ENDIF
  CLOSE(POINTS_CHANNEL)
  PRINT*,'CONV_CDWACA: Total of CDW + ACAR TEMP OBS: ',NUMOBS
  IF (NUMOBS .GT. MAXOBS) THEN
    PRINT*,'CONV_CDW_ACA: Data array is too small, MAXOBS needs enlarge ',NUMOBS,MAXOBS
    STOP
  ENDIF

  ! 1. WIND:
  OBSTYP = 'wind'
  CALL OPEN_LAPSPRD_FILE_READ(POINTS_CHANNEL,SYSTEM_IN4TIME,EXTEND,STATUS)
  IF (STATUS .NE. 1) THEN
    PRINT*,'CONV_CDWACA: No ACAR (PIREP) wind data'
  ELSE
    STATUS = 0
    DO
      CALL READ_ACARS_OB(POINTS_CHANNEL,OBSTYP,OBSLAT,OBSLON,OBSELV,OBSDIR,OBSSPD, &
                               ASCTIM,0,STATUS)
      IF (STATUS .NE. 0) EXIT
      NUMOBS = NUMOBS+1
      OBARRY(1:7,NUMOBS) = RVALUE_MISSING
      OBARRY(1,NUMOBS) = OBSLAT
      OBARRY(2,NUMOBS) = OBSLON
      OBARRY(3,NUMOBS) = OBSELV
      CALL DISP_TO_UV(OBSDIR,OBSSPD,OBSTMP,OBSNON)
      CALL UVTRUE_TO_UVGRID(OBSTMP,OBSNON,OBSDIR,OBSSPD,OBSLON)
      OBARRY(5,NUMOBS) = OBSDIR
      OBARRY(6,NUMOBS) = OBSSPD
      OBSINT(1,NUMOBS) = 41		! USE BUFR REPORT TYPE CODE: 
                                        ! ACARS WIND
      OBSINT(2,NUMOBS) = 230		! PILOR REPORT: TEMPERATURE
      CALL CV_ASC_I4TIME(ASCTIM,OBSINT(3,NUMOBS))
      PRINT*,'ACAR WIND: ',OBSLAT,OBSLON,OBSELV,OBSDIR,OBSSPD,OBSINT(3,NUMOBS)
    ENDDO
  ENDIF
  CLOSE(POINTS_CHANNEL)
  PRINT*,'CONV_CDWACA: Total of CDW + ACAR TEMP + ACAR WIND OBS: ',NUMOBS
  IF (NUMOBS .GT. MAXOBS) THEN
    PRINT*,'CONV_CDWACA: Data array is too small, MAXOBS needs enlarge ',NUMOBS,MAXOBS
    STOP
  ENDIF

  IF (NUMOBS .EQ. 0) RETURN

  IF (FORMAT_REQUEST .EQ. 'BUFR') THEN
    CALL BUFR_CDWACA(NUMOBS,OBARRY,OBSINT)
  ELSE IF (FORMAT_REQUEST .EQ. 'WRF' ) THEN
    CALL WRFD_CDWACA(NUMOBS,OBARRY,OBSINT)
  ENDIF

END SUBROUTINE CONV_CDWACA
