      subroutine get_laps_lat_lon(dir,ext,nx,ny,lat,lon,istatus)
c
c *** Modified from code generated by gennet (B. Schwartz, FSL)
c
      implicit none
c
      include 'netcdf.inc'
c
      integer*4 nx,ny
      real*4 lat(nx,ny),
     .       lon(nx,ny)
c
      integer*4 len,elen,i,istatus
      integer*4 start(10),count(10)
     .         ,ncid,ntp,nvdim,nvs,lenstr,ndsize,rcode
      integer   vdims(10)
c
      character*(*) dir
      character*(*) ext
      character*31  dummy
c
      logical exists
c_______________________________________________________________________________
c
c *** Create netcdf file name and check for existence.
c
      len=index(dir,' ')-1
      if (dir(len:len) .ne. '/') then
          dir(len+1:len+1)='/'
          len=len+1
      endif
      elen=index(ext,' ')-1
      inquire(file=dir(1:len)//'static.'//ext(1:elen),exist=exists)
      if (.not. exists) then
         print *,' *** LAPS static file does not exist:  ',
     .           dir(1:len)//'static.'//ext(1:elen)
         istatus=0
         return
      endif
c
c *** Open netcdf file.
c
      ncid=ncopn(dir(1:len)//'static.'//ext(1:elen),ncnowrit,rcode)
c
c *** Statements to fill lat, lon.
c
      call ncvinq(ncid,1,dummy,ntp,nvdim,vdims,nvs,rcode)
      lenstr=1
      do i=1,nvdim
         call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
         lenstr=lenstr*ndsize
         start(i)=1
         count(i)=ndsize
      enddo
      call ncvgt(ncid,1,start,count,lat,rcode)
c
      call ncvinq(ncid,2,dummy,ntp,nvdim,vdims,nvs,rcode)
      lenstr=1
      do i=1,nvdim
         call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
         lenstr=lenstr*ndsize
         start(i)=1
         count(i)=ndsize
      enddo
      call ncvgt(ncid,2,start,count,lon,rcode)
c
c *** Close netcdf file.
c
      call ncclos(ncid,rcode)
c
      istatus=1
      return
      end
c
c===============================================================================
c
      subroutine get_laps_wind(dir,i4time,ext,nx,ny,nz,uw,vw,istatus)
c
c *** Modified from code generated by gennet (B. Schwartz, FSL)
c
      implicit none
c
      include 'netcdf.inc'
c
      integer*4 nx,ny,nz
      real*4 uw(nx,ny,nz)   !LAPS 3d u-wind (m/s)
     .      ,vw(nx,ny,nz)   !LAPS 3d v-wind (m/s)
     .      ,gd(nx,ny,nz)
c
      integer*4 len,elen,i4time,i,j,k,istatus
      integer*4 start(10),count(10),
     .          ncid,ntp,nvdim,nvs,lenstr,ndsize,rcode
      integer   vdims(10)
c
      character*(*) dir,ext
      character*500 ldir,lext,fname
      character*31  dummy
      character*9   atime
c
      logical exists
c_______________________________________________________________________________
c
c *** Create netcdf file name and check for existence.
c
      call make_fnam_lp(i4time,atime,istatus)
      ldir=dir
      lext=ext
      len=index(ldir,' ')-1
      if (ldir(len:len) .ne. '/') then
         ldir(len+1:len+1)='/'
         len=len+1
      endif
      fname=ldir(1:len)//atime
      len=len+9
c
      elen=index(lext//' ',' ')-1
      if (elen .gt. 0) then
         fname=fname(1:len)//'.'//lext(1:elen)
         len=len+elen+1
      endif
      inquire(file=fname(1:len),exist=exists)
      if (.not. exists) then
         print *,' *** LAPS 3d wind file does not exist:  ',
     .           fname(1:len)
         istatus=0
         return
      endif
c
c *** Open netcdf file.
c
      ncid=ncopn(fname(1:len),ncnowrit,rcode)
c
c *** Statements to fill 3d u-wind (uw).
c
      call ncvinq(ncid,1,dummy,ntp,nvdim,vdims,nvs,rcode)
      lenstr=1
      do i=1,nvdim
         call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
         lenstr=lenstr*ndsize
         start(i)=1
         count(i)=ndsize
      enddo
      call ncvgt(ncid,1,start,count,gd,rcode)
      do k=1,nz
      do j=1,ny
      do i=1,nx
         uw(i,j,k)=gd(i,j,nz+1-k)
      enddo
      enddo
      enddo
c
c *** Statements to fill 3d v-wind (vw).
c
      call ncvinq(ncid,2,dummy,ntp,nvdim,vdims,nvs,rcode)
      lenstr=1
      do i=1,nvdim
         call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
         lenstr=lenstr*ndsize
         start(i)=1
         count(i)=ndsize
      enddo
      call ncvgt(ncid,2,start,count,gd,rcode)
      do k=1,nz
      do j=1,ny
      do i=1,nx
         vw(i,j,k)=gd(i,j,nz+1-k)
      enddo
      enddo
      enddo
c
c *** Close netcdf file.
c
      call ncclos(ncid,rcode)
c
      istatus=1
      return
      end
c
c===============================================================================
c
c     subroutine get_laps_lt1(dir,i4time,ext,nx,ny,nz,nfld,fldid
c    .                      ,grid,istatus)
c
c *** Modified from code generated by gennet (B. Schwartz, FSL)
c
c     implicit none
c
c     include 'netcdf.inc'
c
c     integer*4 nx,ny,nz,nfld
c     real*4 grid(nx,ny,nz,nfld),gd(nx,ny,nz)
c     integer*4 fldid(nfld)
c
c     integer*4 len,elen,i4time,i,j,k,n,istatus
c     integer*4 start(10),count(10)
c    .         ,ncid,ntp,nvdim,nvs,lenstr,ndsize,rcode
c     integer   vdims(10)
c
c     character*(*) dir
c     character*500 ldir
c     character*(*) ext
c     character*500 lext
c     character*31  dummy
c     character*9   atime
c
c     logical exists
c_______________________________________________________________________________
c
c *** Create netcdf file name and check for existence.
c
c     call make_fnam_lp(i4time,atime,istatus)
c     ldir=dir
c     len=index(ldir,' ')-1
c     if (ldir(len:len) .ne. '/') then
c        ldir(len+1:len+1)='/'
c        len=len+1
c     endif
c     lext=ext
c     elen=index(lext,' ')-1
c     if (lext(1:3) .eq. 'lga') then
c        inquire(file=ldir(1:len)//atime//'0000.'//lext(1:elen)
c    .          ,exist=exists)
c     elseif (elen .gt. 0) then
c        inquire(file=ldir(1:len)//atime//'.'//lext(1:elen)
c    .          ,exist=exists)
c     else
c        inquire(file=ldir(1:len)//atime,exist=exists)
c     endif
c     if (.not. exists) then
c        if (lext(1:3) .eq. 'lga') then
c           print *,' *** LAPS 3d file does not exist:  '
c    .             ,ldir(1:len)//atime//'0000.'//lext(1:elen)
c        elseif (elen .gt. 0) then
c           print *,' *** LAPS 3d file does not exist:  '
c    .             ,ldir(1:len)//atime//'.'//lext(1:elen)
c        else
c           print *,' *** LAPS 3d file does not exist:  '
c    .             ,ldir(1:len)//atime
c        endif
c        istatus=0
c        return
c     endif
c
c *** Open netcdf file.
c
c     if (lext(1:3) .eq. 'lga') then
c        ncid=ncopn(ldir(1:len)//atime//'0000.'//lext(1:elen)
c    .       ,ncnowrit,rcode)
c     elseif (elen .gt. 0) then
c        ncid=ncopn(ldir(1:len)//atime//'.'//lext(1:elen)
c    .       ,ncnowrit,rcode)
c     else
c        ncid=ncopn(ldir(1:len)//atime,ncnowrit,rcode)
c     endif
c
c     do n=1,nfld
c
c ***** Statements to fill requested 3d field.
c
c J. Smart 8/98. fldid returns the number of fields available in netCDF file.

c     call ncvinq(ncid,fldid,dummy,ntp,nvdim,vdims,nvs,rcode)

c     do n=1,fldid
c        lenstr=1
c        do i=1,nvdim
c           call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
c           lenstr=lenstr*ndsize
c           start(i)=1
c           count(i)=ndsize
c        enddo
c        call ncvgt(ncid,fldid(n),start,count,gd,rcode)
c
c ****** Invert grid in vertical.
c
c        do k=1,nz
c        do j=1,ny
c        do i=1,nx
c           grid(i,j,k,n)=gd(i,j,nz+1-k)
c        enddo
c        enddo
c        enddo
c
c     enddo
c
c *** Close netcdf file.
c
c     call ncclos(ncid,rcode)
c
c     istatus=1
c     return
c     end
c
c===============================================================================
c
      subroutine get_laps_2d(dir,i4time,ext,nx,ny,nfld,fldid
     .                      ,grid,istatus)
c
c *** Modified from code generated by gennet (B. Schwartz, FSL)
c
      implicit none
c
      include 'netcdf.inc'
c
      integer*4 nx,ny,nfld
      real*4 grid(nx,ny,nfld)
      integer*4 fldid(nfld)
c
      integer*4 len,elen,i4time,i,n,istatus
      integer*4 start(10),count(10)
     .         ,ncid,ntp,nvdim,nvs,lenstr,ndsize,rcode
      integer   vdims(10)
c
      character*(*) dir,ext
      character*500 ldir,lext,fname
      character*31  dummy
      character*9   atime
c
      logical exists
c_______________________________________________________________________________
c
c *** Create netcdf file name and check for existence.
c
      call make_fnam_lp(i4time,atime,istatus)
      ldir=dir
      len=index(ldir,' ')-1
      if (ldir(len:len) .ne. '/') then
         ldir(len+1:len+1)='/'
         len=len+1
      endif
      fname=ldir(1:len)//atime
      len=len+9
c
      lext=ext
      elen=index(lext,' ')-1
      if (elen .gt. 0) then
         fname=fname(1:len)//'.'//lext(1:elen)
         len=len+elen+1
      endif
      inquire(file=fname(1:len),exist=exists)
      if (.not. exists) then
         print *,' *** LAPS surface file does not exist:  '
     .          ,fname(1:len)
         istatus=0
         return
      endif
c
c *** Open netcdf file.
c
      ncid=ncopn(fname(1:len),ncnowrit,rcode)
c
      do n=1,nfld
c
c *** Statements to fill requested 2d field.
c
         call ncvinq(ncid,fldid(n),dummy,ntp,nvdim,vdims,nvs,rcode)
         lenstr=1
         do i=1,nvdim
            call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
            lenstr=lenstr*ndsize
            start(i)=1
            count(i)=ndsize
         enddo
         call ncvgt(ncid,fldid(n),start,count,grid(1,1,n),rcode)
c
      enddo
c
c *** Close netcdf file.
c
      call ncclos(ncid,rcode)
c
      istatus=1
      return
      end
c
c===============================================================================
c
      subroutine get_laps_sfc_elev(dir,ext,nx,ny,sht,istatus)
c
c *** Modified from code generated by gennet (B. Schwartz, FSL)
c
      implicit none
c
      include 'netcdf.inc'
c
      integer*4 nx,ny
      real*4 sht(nx,ny)
c
      integer*4 len,elen,i,istatus
      integer*4 start(10),count(10)
     .         ,ncid,ntp,nvdim,nvs,lenstr,ndsize,rcode
      integer   vdims(10)
c
      character*(*) dir
      character*500 ldir
      character*(*) ext
      character*500 lext
      character*31  dummy
c
      logical exists
c_______________________________________________________________________________
c
c *** Create netcdf file name and check for existence.
c
      ldir=dir
      len=index(ldir,' ')-1
      if (ldir(len:len) .ne. '/') then
         ldir(len+1:len+1)='/'
         len=len+1
      endif
      lext=ext
      elen=index(lext,' ')-1
      inquire(file=ldir(1:len)//'static.'//lext(1:elen),exist=exists)
      if (.not. exists) then
         print *,' *** LAPS static file does not exist:  '
     .          ,ldir(1:len)//'static.'//lext(1:elen)
         istatus=0
         return
      endif
c
c *** Open netcdf file.
c
      ncid=ncopn(ldir(1:len)//'static.'//lext(1:elen),ncnowrit,rcode)
c
c *** Statements to fill sht.
c
      call ncvinq(ncid,3,dummy,ntp,nvdim,vdims,nvs,rcode)
      lenstr=1
      do i=1,nvdim
         call ncdinq(ncid,vdims(i),dummy,ndsize,rcode)
         lenstr=lenstr*ndsize
         start(i)=1
         count(i)=ndsize
      enddo
      call ncvgt(ncid,3,start,count,sht,rcode)
c
c *** Close netcdf file.
c
      call ncclos(ncid,rcode)
c
      istatus=1
      return
      end
