
!       integer icolors(8)/252,245,202,15,110,253,205,206/
        integer icolors(12)
        data icolors/11,5,13,3,8,9,10,16,17,26,27,1/

!       icolors_tt(0)  = deep blue    (   )     Map background
!       icolors_tt(1)  = green        (   )     Overlay 1
!       icolors_tt(2)  = orange       (   )     Overlay 2
!       icolors_tt(3)  = light blue   (   )     Overlay 3
!       icolors_tt(13) = red          (111)
!       icolors_tt(14) = yellow       (253)
!       icolors_tt(15) = white        (229)

        integer icolors_tt(0:15)
        data icolors_tt/4,3,8,11,4,5,6,7,8,9,10,11,12,2,7,1/
