********      Constants for program processing     ********************

	Integer Natm
	Parameter (Natm = 1)	! number of dependent atmospheres
	Integer Nlevel
	Parameter (Nlevel = 100) ! number of levels
	Integer Nw
	Parameter (Nw = 300)	! number of standard water levels (-1)
	Integer Nangle
	Parameter (Nangle = 6)	! number of look angles
	Integer Nchan
	Parameter (Nchan = 22)	! number of channels 

	Integer Nwet
	Parameter (Nwet = 5)   ! = number of predictors
	Integer Ndry
	Parameter (Ndry = 5)   ! = number of predictors
	Integer NOzo
	Parameter (NOzo = 5)   ! = number of predictors

