

	type sfcob
          sequence
          real sfct_k
          real sfct_f

          real t_f
          real t_ea_f

          real td_f
          real td_ea_f

          real dd_deg
          real dd_ea_deg

          real ff_kt
          real ff_ea_kt

          real ri
          real rj
          real elev_diff
          real ldf

          integer i
          integer j

          character*20 stn20
          character*3  stn3

	end type sfcob

