subroutine adrf1d( n, a, np, adu )
!***************************************************************
!***************************************************************
!** This routine was generated by the                         **
!** Tangent linear and Adjoint Model Compiler,  TAMC 5.3.2    **
!***************************************************************
!***************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! define common blocks
!==============================================
!==============================================
! define arguments
!==============================================
real a
integer n
real adu(n)
integer np

!==============================================
! define local variables
!==============================================
real adr(n)
integer i
integer ip
integer ip1
real one_a

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES
!----------------------------------------------
do ip1 = 1, n
  adr(ip1) = 0.
end do

!----------------------------------------------
! ROUTINE BODY
!----------------------------------------------
one_a = 1.-a
do ip = np, 1, -1
  do i = 1, n-1
    adr(i) = adr(i)+adu(i)*one_a
    adu(i+1) = adu(i+1)+adu(i)*a
    adu(i) = 0.
  end do
  if (ip .eq. 1) then
    adr(n) = adr(n)+adu(n)/(1.+a)
    adu(n) = 0.
  else
    adr(n-1) = adr(n-1)-adu(n)*(one_a*a**3/(1.-a**2)**2)
    adr(n) = adr(n)+adu(n)*(one_a/(1.-a**2)**2)
    adu(n) = 0.
  endif
  do i = n, 2, -1
    adu(i) = adu(i)+adr(i)*one_a
    adr(i-1) = adr(i-1)+adr(i)*a
    adr(i) = 0.
  end do
  if (ip .eq. 1) then
    adu(1) = adu(1)+adr(1)*one_a
    adr(1) = 0.
  else if (ip .eq. 2) then
    adu(1) = adu(1)+adr(1)/(1.+a)
    adr(1) = 0.
  else
    adu(2) = adu(2)-adr(1)*(one_a*a**3/(1.-a**2)**2)
    adu(1) = adu(1)+adr(1)*(one_a/(1.-a**2)**2)
    adr(1) = 0.
  endif
end do

end subroutine adrf1d


